### ISSUE TITLE
SoftLayer_Exception_ObjectNotFound when deleting DNS record

### ISSUE THREAD

**Issue by fabiograssofy** [softlayer/softlayer-python#1000]
When try to delete a DNS record using slcli, I receive this error:

`SoftLayerAPIError(SoftLayer_Exception_ObjectNotFound): Unable to find object with id of 'xxxxxxxxx'.
`

The same operation made via curl works fine:

`curl -# -X GET https://username:api_key@api.service.softlayer.com/rest/v3/SoftLayer_Dns_Domain_ResourceRecord/xxxxxxxxx/deleteObject.json
`

I've opened a ticket on Softlayer and the support suggested to open a bug issue here

### Environment Information
Operating System: tested on CentOS Linux 7.4.1708 and Ubuntu 14.04.5 LTS
softlayer-python version (slcli --version): tested with 5.5.0 and 5.3.2

**Comment by acamacho82** [comment]
I was only able to reproduce the error when I sent the recordId twice. 

```
$ slcli dns record-remove 11223344
This action cannot be undone! Type "yes" or press Enter to abort: yes

$ slcli dns record-remove 11223344
This action cannot be undone! Type "yes" or press Enter to abort: yes
SoftLayerAPIError(SoftLayer_Exception_ObjectNotFound): Unable to find object with id of '11223344'.
```
I think the `slcli dns record-remove` command is working as expected, I was able to delete DNS records  like A, AAA, MX, TXT, SRV, SPF.

slcli version 5.5.0
