### ISSUE TITLE
VSI upgrade improvements

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#1001]
We need a way to upgrade VSIs to allow more storage volumes. 

Currently we can upgrade CPU/RAM/Network, but not the disk. 

Assumption here is this will only work with new family sized VSI, this change doesn't need to be compatible with the older models.

**Comment by newmocart** [comment]
Hi there,

It's available via order manager.

Example 

https://sldn.softlayer.com/python/vsi_flavor_add_second_disk/

**Comment by allmightyspiff** [comment]
This was added in [5.9.0](https://github.com/softlayer/softlayer-python/releases/tag/v5.9.0) 

- #1308  Pull request
- #1295  Github Issue
