### ISSUE TITLE
Where can i find the docs on the definition of faultCode and faultString ?

### ISSUE THREAD

**Issue by yhuanghamu** [softlayer/softlayer-python#1017]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):

**Comment by acamacho82** [comment]
I think that this kind of questions should be posted in sites like [stackoverflow](https://stackoverflow.com), did you review https://docs.python.org/3/library/xmlrpc.client.html#fault-objects?

**Comment by allmightyspiff** [comment]
For SoftLayer API errors, the definition is found here: https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/exceptions.py#L19

The exceptions are built from the transport call itself, and they differ slightly based on wether you are using XML or REST api.

XML: https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/transports.py#L224
REST: https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/transports.py#L390

The faultCode might be different when using a different endpoint, but the faultString should be similar.

**Comment by yhuanghamu** [comment]
Those are SoftLayerAPIError that i got
``` 
SoftLayerAPIError(SoftLayer_Exception_NotFound): A billing item is required to process a cancellation.
```
```
SoftLayerAPIError(SoftLayer_Exception_ObjectNotFound): Unable to find object with id of '3424342'.
```
```
SoftLayerAPIError(SoftLayer_Exception_Public): This cancellation could not be processed please contact support.This cancellation could not be processed. Please contact support. There is currently an active transaction.
```
I can't find definition of those faultcode and faultString in python client repo, I guess they might be from other apis, or you internal docs, Just wonder if you can provide more docs on those definition.

**Comment by allmightyspiff** [comment]
Unfortunately there is no documentation on the wide variety of errors the SLAPI might send out :(
