### ISSUE TITLE
[CLI  Feature Request] ability to set ticket priority 

### ISSUE THREAD

**Issue by b52src** [softlayer/softlayer-python#1019]
Hello,

it would be nice to have the ability to set Ticket priority from the CLI for paid support accounts

### Expected Behavior
a --priority INTEGER option to set Ticket Priority  when creating a ticket 
Example: `slcli ticket create --title='TESTING' --subject-id=1021 --priority=1 --body='help'`

### Actual Behavior
There is no way currently available to set Ticket Priority it must be done via the API or the control portal.

### Environment Information
Operating System: Mac OSX 10.13.6
softlayer-python version (`slcli --version`):slcli (SoftLayer Command-line), version 5.2.11

**Comment by allmightyspiff** [comment]
### TODO
- `slcli ticket create` should be able to set priority
- `slcli ticket updated` should be able to set priority
- `slcli ticket list` should be able to view priority
- `slcli ticket detail` should be able to view priority
- `slcli ticket summary` should be able to view priority

**Comment by allmightyspiff** [comment]
Will be in the v5.5.2 release
