### ISSUE TITLE
Price estimate in slcli vs create --test omits the base price of the flavor

### ISSUE THREAD

**Issue by jtapsl** [softlayer/softlayer-python#1033]
### Expected Behavior
The price estimate when adding the --test flag to slcli vs create should show the correct retail price.

### Actual Behavior
The price estimate includes the price of add-ons such as disks, network speed, etc, but omits the base cost of the flavor.

$ slcli vs create --hostname pricetest --domain example.org --datacenter wdc01 --os CENTOS_7_64 --billing monthly --flavor B1_2X8X25 --private --test | tee /tmp/pricetest.txt
CentOS 7.x - Minimal Install (64 bit)                  0.00  
25 GB (SAN)                                            0.00  
Reboot / Remote Console                                0.00  
10 Mbps Private Network Uplink                         0.00  
0 GB Bandwidth Allotment                               0.00  
1 IP Address                                           0.00  
Host Ping and TCP Service Monitoring                   0.00  
Email and Ticket                                       0.00  
Automated Reboot from Monitoring                       0.00  
Unlimited SSL VPN Users & 1 PPTP VPN User per account  0.00  
Nessus Vulnerability Assessment & Reporting            0.00  
Total monthly cost                                     0.00  
 -- ! Prices reflected here are retail and do not take account level discounts and are not guaranteed.

### Environment Information
Operating System: Red Hat Enterprise Linux Workstation release 7.5 (Maipo)
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.5.2

**Comment by allmightyspiff** [comment]
This fix will be included in the 5.5.3 release
