### ISSUE TITLE
prompt_toolkit 2

### ISSUE THREAD

**Issue by carlwgeorge** [softlayer/softlayer-python#1042]
I'm working on updating the prompt_toolkit package in Fedora to version 2, which is required to update ipython to version 7.  However, some packages, including python2-softlayer and python3-softlayer, still require prompt_toolkit 1.  What is the status of this project migrating to prompt_toolkit 2?

https://python-prompt-toolkit.readthedocs.io/en/stable/pages/upgrading.html

**Comment by allmightyspiff** [comment]
I'll look into the work required to update to the newest prompt_toolkit.
