### ISSUE TITLE
loadbal command cannot get IBM Cloud Load Balancer

### ISSUE THREAD

**Issue by tanucojp** [softlayer/softlayer-python#1047]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
"slcli loadbal list" show a list of Load Balancers

### Actual Behavior
Not shown.

$ slcli loadbal list
:....:.............:..........:.............:....................:......:
: ID : VIP Address : Location : SSL Offload : Connections/second : Type :
:....:.............:..........:.............:....................:......:
:....:.............:..........:.............:....................:......:

But when using call-api, it shows a list.

$ slcli call-api Network_LBaaS_LoadBalancer getAllObjects
:...........:...................................................:...........................:........................:........:..........:............:...........................:......................:.................:....................:.......................:......................................:
: accountId :                      address                      :         createDate        :       datacenter       :   id   : isPublic : locationId :         modifyDate        :         name         : operatingStatus : provisioningStatus : useSystemPublicIpPool :                 uuid                 :
:...........:...................................................:...........................:........................:........:..........:............:...........................:......................:.................:....................:.......................:......................................:
:  xxxxxxxx  : xxxxxxxxxx-tok02.lb.bluemix.net : 2018-09-27T18:21:17+09:00 : :..........:.........: : xxxxxxxxx :    1     :   xxxxxx  : 2018-10-03T18:49:34+09:00 : xxxxxxxxxxxxxxxxx :      ONLINE     :       ACTIVE       :           0           : xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx :

"slcli loadbal" does not support IBM Cloud Load Balancer?

### Environment Information
Operating System: Ubuntu
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.5.2

**Comment by acamacho82** [comment]
Yes, currently `slcli loadbal` only supports local load balancers.

I could recommend you to use `slcli call-api` in the meanwhile.

```
slcli call-api SoftLayer_Network_LBaaS_LoadBalancer getAllObjects --mask=id,uuid,name,description,address,datacenter.name,operatingStatus,isPublic
```
To retrieve the same information in json format then use the following:
```
slcli --format=json call-api SoftLayer_Network_LBaaS_LoadBalancer getAllObjects
```

**Comment by allmightyspiff** [comment]
This feature will be included in the next slcli release
