### ISSUE TITLE
Update reference from KL to IBM Cloud Docs

### ISSUE THREAD

**Issue by gudrun-wolfgram** [softlayer/softlayer-python#1056]
In the https://softlayer-api-python-client.readthedocs.io/en/latest/api/managers/image/ topic, there's a reference to product information. The Knowledge Layer reference is no longer current. Please update to reference the following IBM Cloud Docs collection for Image Templates: 
https://console.bluemix.net/docs/infrastructure/image-templates/image_index.html

Thanks!

**Comment by allmightyspiff** [comment]
Updated.
