### ISSUE TITLE
Support for SoftLayer_Hardware_Server::toggleManagementInterface

### ISSUE THREAD

**Issue by dnwe** [softlayer/softlayer-python#1059]
### Expected Behavior

The [SoftLayer_Hardware_Server::toggleManagementInterface](https://softlayer.github.io/reference/services/SoftLayer_Hardware_Server/toggleManagementInterface/) API call should be available in the softlayer-python client to provide feature parity with the [softlayer-go](https://github.com/softlayer/softlayer-go/issues/116) client.

### Actual Behavior

The [SoftLayer_Hardware_Server::toggleManagementInterface](https://softlayer.github.io/reference/services/SoftLayer_Hardware_Server/toggleManagementInterface/) is not currently supported.

### Environment Information
Operating System: all
softlayer-python version (`slcli --version`): 5.6.0

**Comment by acamacho82** [comment]
I recommend try with the following code lines:

```python
hwId = 1122334 
client['Hardware_Server'].toggleManagementInterface(False, id=hwId)
```

You can also use the `slcli call-api` command to toggle the IPMI interface.

```bash
$ slcli call-api Hardware_Server toggleManagementInterface --id=1122334  True

```
