### ISSUE TITLE
Update slcli hw edit port speed

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#1068]
https://softlayer.github.io/reference/services/SoftLayer_Hardware_Server/setPrivateNetworkInterfaceSpeed/

*NEW! Behavior on January 4th, 2019*

Biggest change is there is a new 'redundancy' flag that should be supported.

**Comment by dkulchinsky** [comment]
@allmightyspiff it looks like the `redundancy` flag is not supported by the python api library and CLI, or am I missing something?

**Comment by allmightyspiff** [comment]
Correct, changing the redundancy isn't currently supported. 
I created #1257  to add that capability.
