### ISSUE TITLE
Property 'powerState' not valid when calling to "slcli server list"

### ISSUE THREAD

**Issue by acamacho82** [softlayer/softlayer-python#1088]
It seems that the mask has set an incorrect property when trying to retrieve the servers and their power status.

```
$ slcli server list --columns=id,hostname,domain,power_state
SoftLayerAPIError(SoftLayer_Exception_WebService_ObjectMask): Property 'powerState' not valid for 'SoftLayer_Hardware_Server'.

```
softlayer-python version (`slcli --version`): 5.6.0 and 5.6.4

**Comment by allmightyspiff** [comment]
does the API keep track of hardware power status? I briefly looked and couldn't find anything obvious, so this might just be a case of code being copy/pasted from the Virtual Guest command and can be removed.
