### ISSUE TITLE
Cannot create vsi on dedicated host after the fix #676 

### ISSUE THREAD

**Issue by acamacho82** [softlayer/softlayer-python#1093]
It seems there is no way to create a vsi on a dedicated host, this is an issue in the fix #676 where `placeOrder` is used in the place of  ` createObject` method.

```
$ slcli vs create -H test01 -D tscupprt.com --host-id 1101 -d mex01 -o UBUNTU_LATEST -c 4 -m 16
This action will incur charges on your account. Continue? [y/N]: y

SoftLayerAPIError(SoftLayer_Exception_Order_Item_Invalid): Invalid price 4 x 2.0 GHz or higher Cores (Dedicated Host) (200313) provided on the order container. Please select a dedicated instance Computing Instance price to order a dedicated instance.
```

The same command works with latest version 5.6.4

These kind of vsi cannot be created through flavors, it is required to select a hostId, cpu and memory.

**Expected Result:**
It should be possible to create vsi on dedicated host by selecting at least a  `--host-id`  , `--cpu`, and `--memory`

**Comment by allmightyspiff** [comment]
fixed in #1096
