### ISSUE TITLE
Feature Request: Python API Pulls Disk Usage Data

### ISSUE THREAD

**Issue by Zman94** [softlayer/softlayer-python#1113]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Python:
`print(vs.get_instance(VM instance))`

```
<Info Dictionary list>, {CPU usage over past week}, <rest of info>
```

### Actual Behavior
```
Just the dictionary
```
### Environment Information
Operating System:
softlayer-python version (`slcli --version`):
`softlayer in /usr/local/lib/python3.6/site-packages (5.7.1)`

The information can be seen in the GUI by clicking on a device, and it would be nice to see usage stats over last period of time for capacity analysis purposes.

**Comment by Zman94** [comment]
This is the wrong github account. My IBM email is zachary.gleason@ibm.com

**Comment by allmightyspiff** [comment]
#1137 adds `slcli vs usage`. However this won't have the useage information added to `get_instance`. You would need to use the new VSManager function `get_summary_data_usage` for that.  I'll release a new version of the slcli Friday where this will all be included.
