### ISSUE TITLE
cannot create static subnet with slcli

### ISSUE THREAD

**Issue by lmgray** [softlayer/softlayer-python#1139]
### Expected Behavior
```
$ slcli subnet create private -h
Usage: slcli subnet create [OPTIONS] **[static|portable]** [public|private] QUANTITY VLAN_ID

  Add a new subnet to your account. Valid quantities vary by type.

  Type    - Valid Quantities (IPv4)
  **static public** - 1, 2, 4, 8, 16, 32, 128, 256
  portable public  - 4, 8, 16, 32
  portable private - 4, 8, 16, 32, 64

  Type    - Valid Quantities (IPv6)
  **static public**  - 64
  portable public - 64

Options:
  --v6, --ipv6  Order IPv6 Addresses
  --test        Do not order the subnet; just get a quote
  -h, --help    Show this message and exit.
```
It's possible through the API so it should be exposed in slcli: https://sldn.softlayer.com/python/order_static_subnet/

### Actual Behavior

```$ slcli subnet create private -h
Usage: slcli subnet create [OPTIONS] [public|private] QUANTITY VLAN_ID

  Add a new subnet to your account. Valid quantities vary by type.

  Type    - Valid Quantities (IPv4)
  public  - 4, 8, 16, 32
  private - 4, 8, 16, 32, 64

  Type    - Valid Quantities (IPv6)
  public  - 64

Options:
  --v6, --ipv6  Order IPv6 Addresses
  --test        Do not order the subnet; just get a quote
  -h, --help    Show this message and exit.
```

### Environment Information
Operating System: Ubuntu 18.04.2 LTS
softlayer-python version (`slcli --version`):  slcli (SoftLayer Command-line), version 5.7.1

**Comment by allmightyspiff** [comment]
I'll add this to our TODO list,  but in the mean time this command should work for ordering a static subnet.


`slcli order place --verify STATIC_IP_ADDRESSES DALLAS10 --complex-type SoftLayer_Container_Product_Order_Network_Subnet 8_STATIC_PUBLIC_IP_ADDRESSES --extras ‘{"endPointIpAddressId": "12345"}’`

**Comment by lmgray** [comment]
Thanks -- in case anyone else is reading this -- one (not so) tricky bit...   to get that "endPointIpAddressId"...

```
$ slcli -C ~/.softlayer.csp subnet lookup 'x.x.x.x' | awk '$1=="id"{print $2}'
12345nnnn

```
