### ISSUE TITLE
property 'contents' is not valid for 'SoftLayer_Ticket' when creating a ticket

### ISSUE THREAD

**Issue by acamacho82** [softlayer/softlayer-python#1147]
Cannot create tickets with `--body` param, this happens when the slcli uses the REST endpoint.

It seems the `contents` in the code below needs to be removed since this property isn't in the  datatype https://sldn.softlayer.com/reference/datatypes/SoftLayer_Ticket/ 

https://github.com/softlayer/softlayer-python/blob/0738549ea64505968dd17b0cc1bbc38b8bc82f7f/SoftLayer/managers/ticket.py#L69-L74

### Actual Behavior

```
$ slcli ticket create --title "Test::SLCI" --subject-id 1001 --body "Example"

SoftLayerAPIError(500): The property 'contents' is not valid for 'SoftLayer_Ticket'.
```

### Environment Information
OS information: ubuntu 18.04, windows 10
softlayer-python version (`slcli --version`): 5.7.1, 5.7.2
end-point: REST

**Comment by allmightyspiff** [comment]
As far as I can tell, `contents` has never been part of the SoftLayer_Ticket datatype ( https://sldn.softlayer.com/reference/services/SoftLayer_Ticket/createStandardTicket/  last updated Nov 28, 2018 ), but I'm not sure why this is suddenly not working... unless it just never worked in REST and only accidentally worked in XML

I think the `contents` in the `new_ticket` object is redundant anyway ( https://sldn.softlayer.com/reference/services/SoftLayer_Ticket/createStandardTicket/ ), as that is passed into `createStandardTicket`.   Try removing that piece and see if this call works in both REST/XML.
