### ISSUE TITLE
slcli vs reboot is not working

### ISSUE THREAD

**Issue by richb-ibm** [softlayer/softlayer-python#1181]
When I try to use slcli to reboot a VSI it tells me it it unable to find the VSI:
```
[root@b8 ~]# slcli vs reboot s31156
Error: Unable to find VS 's31156'
```
but slcli finds the VSI fine if I run `slcli vs detail` or `slcli vs ready`:
```
[root@b8 ~]# slcli vs ready s31156
READY
```

### Expected Behavior

VSI is rebooted.

### Actual Behavior

slcii can't find an existing VSI.

### Environment Information
Operating System: RHEL 7.6
softlayer-python version (`slcli --version`): 5.8.0

I first noticed this issue on version 5.5.0 so upgraded to 5.8.0 to verify it wasn't an already fixed issue.

**Comment by allmightyspiff** [comment]
This fix will be included in the next release
