### ISSUE TITLE
Feature Request: 'slcli user' to edit user's VPN subnet

### ISSUE THREAD

**Issue by jeswant** [softlayer/softlayer-python#1239]
### Expected Behavior
Is there a slcli way to grant/revoke VPN subnet access to a user?
I couldn't find it in here: https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/CLI/user/

### Actual Behavior
Currently, I edit the VPN subnets via cloud.ibm.com > Manage > IAM > Users > select the user > Classic Infrastructure > VPN Subnets > Select a subnet > Save

### Environment Information
Operating System: Mac OS X 10.15.1
slcli (SoftLayer Command-line), version 5.8.0

**Comment by allmightyspiff** [comment]
Currently this doesn't exist in the CLI, but would certainly be a good feature to add.

You would need to use [SoftLayer_Network_Service_Vpn_Overrides/createObjects](https://sldn.softlayer.com/reference/services/SoftLayer_Network_Service_Vpn_Overrides/createObjects/) to manage these.

If you need to do this soon, something like this in python should work for adding a subnet for a user.
```python
client = SoftLayer.Client()
result = client.call('SoftLayer_Network_Service_Vpn_Overrides',  'createObjects', [{"userId":1234, "subnetId": 4444}]
```
