### ISSUE TITLE
Snap version is over 1000 revisions old...suggest updating the snap. 

### ISSUE THREAD

**Issue by kz6fittycent** [softlayer/softlayer-python#1252]
Let me know if you'd like any assistance updating the snap and which release is appropriate for "stable" release. 

Last stable release was NOV 2018, snap version: 383. Latest revision in "edge" which pulls from Git repo is 1422. These numbers do NOT match what the actual software version is; snaps use versions based on "builds". 

I can submit a PR but releasing a new "stable" version is pretty easy, depending on what you consider stable. 

@allmightyspiff and I have collaborated in the past as I built the original snap when working at SoftLayer.

**Comment by allmightyspiff** [comment]
@kz6fittycent 
https://build.snapcraft.io/user/softlayer/softlayer-python/884060

is that not building 5.8.7?
I think I keep forgetting to update the snap/snapcraft.yaml file though with the new version, so that might be part of the problem?

**Comment by kz6fittycent** [comment]
It's building but in the dashboard you can move the latest build to other release stages. Right now, your latest build is sitting in edge, but can be moved up to stable it beta or candidate depending on what you want to do. I can do it for you but I'm not certain if that's what you want.

**Comment by allmightyspiff** [comment]
If there isn't anything I need to change in the softlayer-python repo, I think I can figure out how to publish the build for now. If your not working with Softlayer anymore, I'd prefer to handle the releasing of versions and all that myself. 

Tricky part is going to be adding it to https://github.com/softlayer/softlayer-python/blob/master/fabfile.py so when I do the release the snap gets created too. 

Anyway, I'll read up on it tomorrow and get a new release out. Thanks for letting me know about this though, I thought it was being auto-updated this whole time.

**Comment by kz6fittycent** [comment]
Those who were subscribed to the edge channel would've seen every build and been updated to the latest version you published/committed on github. Those running stable wouldn't.

No problem, I meant to bring this to your attention a lot sooner.

**Comment by allmightyspiff** [comment]
Should be updated now. I'm going to leave this issue open until I figure out a good way to automate this release process.
```
chris@SPF-WIN10:~/Source/softlayer-python$ snapcraft status slcli
Track    Arch     Channel    Version    Revision
latest   amd64    stable     5.8.1+git  1422
                  candidate  ^          ^
                  beta       ^          ^
                  edge       5.8.1+git  1422
         arm64    stable     5.8.1+git  1426
                  candidate  ^          ^
                  beta       ^          ^
                  edge       5.8.1+git  1426
         armhf    stable     5.8.1+git  1425
                  candidate  ^          ^
                  beta       ^          ^
                  edge       5.8.1+git  1425
         i386     stable     5.8.1+git  1423
                  candidate  ^          ^
                  beta       ^          ^
                  edge       5.8.1+git  1423
         ppc64el  stable     5.8.1+git  1424
                  candidate  ^          ^
                  beta       ^          ^
                  edge       5.8.1+git  1424
         s390x    stable     5.8.1+git  1421
                  candidate  ^          ^
                  beta       ^          ^
                  edge       5.8.1+git  1421
```
