### ISSUE TITLE
HW edit: Add redundancy flag for changing port speed

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#1257]
#1068 

`slcli hw edit` should have an option to set the redundancy flag on https://sldn.softlayer.com/reference/services/SoftLayer_Hardware_Server/setPrivateNetworkInterfaceSpeed/ (and the public one)

add a flag for `--redundant/--degraded` that can only be used when setting public/private port speed.
If set, passes "redundant"/"degraded" to the setPrivateNetworkInterfaceSpeed API.

**Comment by dkulchinsky** [comment]
thanks for tracking this @allmightyspiff 

would be great if the `slcli hw detail` output would show `redundant/degraded`
