### ISSUE TITLE
"iter" param should be allowed within manager's methods

### ISSUE THREAD

**Issue by goldyfruit** [softlayer/softlayer-python#1262]
Hi guys,

I'm trying to use as much as I can the managers. Using the `order` manager gave me some hard time because of the `iter` parameter not usable via the `list_items()` method for example.

`list_items()` method only takes `filter` and `mask` as argument.

### My tests
```
return self.order.list_items(pkg_name, filter=filter, mask=mask)
```
Using the data returned by this method with Ansible return this error even if the returned value is a `dict`:
```
super(SoftLayerListResult, self).__init__(items)\nTypeError: 'NoneType' object is not iterable\n",
```

By using directly the `call()` method with `iter=True` Ansible is able to return the data from API.
```
return self.client.call("Product_Package", "getItems", id=pkg_id,
                        filter=filter, mask=mask, iter=True)
```

### Question

What will be the best way to have `iter` parameter usable with the manager's methods?

### Environment Information
Operating System: Fedora 31
softlayer-python version (`slcli --version`): v5.8.7

**Comment by allmightyspiff** [comment]
TODO:

There are a few methods in the ordering manager that following this pattern that should be updated.

```python
def list_items(self, package_keyname, **kwargs):
        """List the items for the given package.

        :param str package_keyname: The package for which to get the items.
        :returns: List of items in the package

        """
        get_kwargs = {}
        get_kwargs['mask'] = kwargs.get('mask', ITEM_MASK)

        if 'filter' in kwargs:
            get_kwargs['filter'] = kwargs['filter']

        package = self.get_package_by_key(package_keyname, mask='id')
        items = self.package_svc.getItems(id=package['id'], **get_kwargs)
        return items
```

Should be something like this:

```python
def list_items(self, package_keyname, **kwargs):
        """List the items for the given package.

        :param str package_keyname: The package for which to get the items.
        :returns: List of items in the package

        """

        if 'mask' not in kwargs:
            kwargs['mask'] =ITEM_MASK

        package = self.get_package_by_key(package_keyname, mask='id')
        items = self.package_svc.getItems(id=package['id'], **kwargs)
        return items
```
Following should be fixed as well.

+ list_categories
+ list_items
+ list_packages
+ list_presets

**Comment by goldyfruit** [comment]
@caberos Thanks :)
