### ISSUE TITLE
Docs links need to be updated in the Block/File help section

### ISSUE THREAD

**Issue by vickmuir** [softlayer/softlayer-python#1305]
During a presentation about the Block and File Storage CLI and UI, two URLs caught my attention that were displayed as part of the SLCLI output. These should be updated to reflect the current domains of the product info and docs.

Old url -> new url
http://www.softlayer.com/block-storage -> https://www.ibm.com/cloud/block-storage
https://console.bluemix.net/docs/infrastructure/BlockStorage/index.html#provisioning -> https://cloud.ibm.com/docs/BlockStorage?topic=BlockStorage-getting-started#provisioning-considerations

### Expected Behavior
When you enter the command like `slcli block order-volume --help`, you should be presented with the usage information, options, and a link to the customer-facing documentation. The link should be pointing to the current IBM Cloud Docs URL.

### Actual Behavior
The link that is shared in the command output is the old bluemix one that was retired 2 years ago.
![image](https://user-images.githubusercontent.com/28069378/87982422-6667a980-ca9c-11ea-9cc0-d7d0f45701ed.png)

### Environment Information
SLCLI

**Comment by allmightyspiff** [comment]
`slcli file volume-order` needs updating as well
