### ISSUE TITLE
Webhook for automatic snap build not enabled - new method

### ISSUE THREAD

**Issue by kz6fittycent** [softlayer/softlayer-python#1362]
@allmightyspiff 

This really isn't an "issue" as much as it will help make building the snap work as intended. 

Go to: [https://snapcraft.io/slcli/settings](https://snapcraft.io/slcli/settings )

Scroll to bottom. 

Click "Set up webhook"

That's it. Now the snap will build automatically. It'll publish to `edge` so you'll still have to move the `edge` version to `stable` when ready. There may be a way to automate this but you'd have to reach out to [forum.snapcraft.io](forum.snapcraft.io) to get that info and set it up. 

![Screenshot from 2020-10-12 22-07-05](https://user-images.githubusercontent.com/14829816/95810784-67912700-0cd7-11eb-8b59-3b33726210ea.png)

**Comment by allmightyspiff** [comment]
https://github.com/softlayer/softlayer-python/blob/master/.github/workflows/release.yml should be updating snapcraft with every release.

I show snapcraft to be on v5.9.1: https://snapcraft.io/slcli/releases

**Comment by allmightyspiff** [comment]
I also get an "Internal Server Error" when updating the webhook for some reason... :( 

![image](https://user-images.githubusercontent.com/7408017/95880039-ae653800-0d3c-11eb-9481-cd8a6593ef43.png)

**Comment by allmightyspiff** [comment]
The snapcraft.yml file you committed fails with the following message:

```
Staging slcli 
Priming slcli 
The command 'slcli' for 'slcli' was resolved to 'bin/slcli'.
The command 'slcli' has been changed to 'bin/slcli'.
Failed to generate snap metadata: Missing required key(s) in snapcraft.yaml: 'summary'. Either specify the missing key(s), or use 'adopt-info' to get them from a part.
Build failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 258, in run
    self.build()
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 247, in build
    env=env)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/build_snap.py", line 100, in run_build_command
    return self.backend.run(args, env=full_env, **kwargs)
  File "/usr/lib/python3/dist-packages/lpbuildd/target/lxd.py", line 537, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lxc', 'exec', 'lp-bionic-i386', '--env', 'LANG=C.UTF-8', '--env', 'SHELL=/bin/sh', '--env', 'SNAPCRAFT_BUILD_INFO=1', '--env', 'SNAPCRAFT_IMAGE_INFO={"build-request-id": "lp-59732571", "build-request-timestamp": "2020-10-13T05:54:22Z", "build_url": "https://launchpad.net/~build.snapcraft.io/+snap/391134a36b9489f4b6b21688eb44155b/+build/1147667"}', '--env', 'SNAPCRAFT_BUILD_ENVIRONMENT=host', '--env', 'http_proxy=http://10.10.10.1:8222/', '--env', 'https_proxy=http://10.10.10.1:8222/', '--env', 'GIT_PROXY_COMMAND=/usr/local/bin/snap-git-proxy', '--', '/bin/sh', '-c', 'cd /build/slcli && linux32 snapcraft']' returned non-zero exit status 2.
Revoking proxy token...
RUN: /usr/share/launchpad-buildd/bin/in-target scan-for-processes --backend=lxd --series=bionic --arch=i386 SNAPBUILD-1147667
Scanning for processes to kill in build SNAPBUILD-1147667
```

I've fixed it so it still based off `core18`, but I had to remove the `adopt-info: slcli` as that seemed to be causing the most problems. 


The releases should be all automated from github actions, but if something is missing from this process, or not working can you explain what is missing a bit?

**Comment by kz6fittycent** [comment]
Submitted new PR to fix. Summary was missing - accident on my part - sorry. 

As far as the webhook, if you reviewed the updated documentation you should be good as long as your published version matches your releases in GH.
