### ISSUE TITLE
Incorrect Values returned from IBM

### ISSUE THREAD

**Issue by eor1994** [softlayer/softlayer-python#1401]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Code used:
import SoftLayer

#SL username and API key
username = ""
api_key = ""
endpoint_url="https://api.softlayer.com/xmlrpc/v3/"

client = SoftLayer.create_client_from_env(username=username,api_key=api_key,endpoint_url=endpoint_url)

print ("get all object storage instances")
storage_instances = client.call('SoftLayer_Account', 'getHubNetworkStorage')   

# Option 1 (slightly less efficient). Get buckets for all COS instances
for storage_instance in storage_instances:
    # filter for COS storage instances
    if storage_instance['storageTypeId'] == '24':
        resp = client.call('SoftLayer_Network_Storage_Hub_Cleversafe_Account',
                       'getBuckets', id=storage_instance['id'])
    print(resp)  

### Expected Behavior
when using the CLI returned value in 'bytesUsed': 2666148982056

### Actual Behavior
Using Python Library
'bytesUsed': -1025708760

### Environment Information
Operating System: Windows 10
softlayer-python version (`slcli --version`):
Python 3.8.2

**Comment by allmightyspiff** [comment]
Looks like somewhere in the python library we are using a signed-32bit int, causing an int overflow error.

To test this, since our account doens't have any storage using that much, just make a fixture for `SoftLayer_Account::getHubNetworkStorage()` and `SoftLayer_Network_Storage_Hub_Cleversafe_Account::getBuckets()` that have a volume with `bytesUsed: 2666148982056` to see if we can at least reproduce the issue that way.

**Comment by allmightyspiff** [comment]
@eor1994  I'm having trouble reproducing this issue on my system. Could you provide the output from the following:

```
import platform
import sys

print(platform.architecture())
print("Max Int: {}".format(sys.maxsize))
getBuckets = {"bytesUsed": 2666148982056}
print("BytesUsed: {}".format(getBuckets['bytesUsed'])) 
print("bytesUsed is a {}".format(type(getBuckets['bytesUsed'])))
print(getBuckets['bytesUsed'])
print("Decimal: %d Int: %i" % (getBuckets['bytesUsed'],getBuckets['bytesUsed']))
```

On Windows 10 (python 3.8.5) I get this:

```
$ python detectArch.py
('32bit', 'WindowsPE')
Max Int: 2147483647
BytesUsed: 2666148982056
bytesUsed is a <class 'int'>
2666148982056
Decimal: 2666148982056 Int: 2666148982056
```
Even though that says 32bit, my copy of Windows 10 is 64bit, which I'm guessing is why python can handle the large int.

On Windows 10 with the Ubuntu shell I get:

```
(py38) [15:02] ~/Source
$> python detectArch.py
('64bit', 'ELF')
Max Int: 9223372036854775807
BytesUsed: 2666148982056
bytesUsed is a <class 'int'>
2666148982056
Decimal: 2666148982056 Int: 2666148982056
```

https://github.com/softlayer/softlayer-python/pull/1403/files#diff-64f3ebf5e26034ec9449b063af04cfa2d3b6a3693cb5aa41ad985153981f62c9 is the test I added specifically to check for this case.


Also, do you get this error with the REST transport as well?

**Comment by eor1994** [comment]
Hi Chris,

Sorry for the late response on this. 

I have tested the code for the system info. I am getting the same data return. 

![result](https://user-images.githubusercontent.com/22214640/104743244-5c6ced80-5743-11eb-918e-3bf893302d69.PNG)

We also ran a test in postman. So this is a request for a buckets attributes directly using the API over a REST connection. As you can see the Bytes used are being returned as a negative number. This indicates it is the API that is wrong, not the client. 


![postman_api](https://user-images.githubusercontent.com/22214640/104735231-45290280-5739-11eb-8e35-5d1f15b7910a.png)


Please advise. 

Thanks for your time.

Regards,
Eoin

**Comment by allmightyspiff** [comment]
@eor1994 Thanks for the update. Since the negative value is coming from the API directly, there isn't much we can do here about that.  What you would want to do is open a [Support Case](https://cloud.ibm.com/unifiedsupport/supportcenter) about this.

That last screenshot showing the negative number in the API results will be needed, and you'll want to put which Network_Straoge_Hub_Cleversafe_Account id you were using. The team that managed Network_Straoge_Hub_Cleversafe_Account  will need to look into why that data is having an int overflow issue on our backend I believe. 

Hope this help.

**Comment by eor1994** [comment]
@allmightyspiff thank you for your guidance on this and time. 

Yes you have been a great help and thank you for the quick response regarding this issue.

**Comment by allmightyspiff** [comment]
@eor1994  you might also want to try switching form the XMLRPC interface to the REST interface. In your `~/.softlayer` file, just set the `endpoint_url` to `endpoint_url = https://api.softlayer.com/rest/v3.1/`

Let me know if that helps or not.

**Comment by eor1994** [comment]
@allmightyspiff  yes positive numbers are indeed returning. 

I will reply with more information and confirm if this indeed has resolved this issue. 

Thank you again for your help.

**Comment by eor1994** [comment]
@allmightyspiff 

Yes the information is now fixed and all values are returning as expected. Appreciate the help and thank you for  your time.

Happy Friday 👍
