### ISSUE TITLE
Incomplete notes field for files in version 5.9.1

### ISSUE THREAD

**Issue by dinogg** [softlayer/softlayer-python#1481]
> Reminder: No username or APIkeys should be added to these issues, as they are public.

**Describe the bug**
In 5.9.1, the `notes` field of the file type is truncated/incomplete.
```
$ pip3 install softlayer==5.9.1
$ slcli --format json file volume-list --columns id,notes,active_transactions 
[
    {
        "id": 103447276,
        "notes": "{\"plugin\":\"ibm-file-",
        "active_transactions": null
    },
...
```

**Expected behavior**
```
$ pip3 install softlayer==5.9.0
$ slcli --format json file volume-list --columns id,notes,active_transactions
[
    {
        "id": 103447276,
        "notes": "{\"plugin\":\"ibm-file-plugin-5f95c99649-m6jvb\",\"region\":\"us-south\",\"cluster\":\"bmou3hkd0dn87e3loiq0\",\"type\":\"Endurance\",\"ns\":\"dedicated-svt\",\"pvc\":\"dedicated-svt-waca-powercube-storage\",\"pv\":\"pvc-f7df5e07-fb3b-11e9-b6b1-8a5542f97f70\",\"storageclass\":\"ibmc-file-retain-silver\",\"reclaim\":\"Retain\"}",
        "active_transactions": null
    },
...
```

**Screenshots**

**Version**
```
$ slcli --version
Current: slcli (SoftLayer Command-line) v5.9.1
Latest:  slcli (SoftLayer Command-line) v5.9.4
```

Thanks in advance for looking into this!

**Comment by allmightyspiff** [comment]
This change was made as part of https://github.com/softlayer/softlayer-python/issues/1322 as I felt long notes made the volume list a bit unreadable.

`slcli file volume-detail <ID>` should still show the entire note.


This command will do basically the same thing
```
$ slcli --format=json call-api SoftLayer_Account getNasNetworkStorage --mask="mask[id,activeTransactions,notes]"
[
    {
        "id": 4917309,
        "notes": "a random notes"
    },
    {
        "id": 22031701,
        "notes": null
    },
```

I could certainly add back the full text for the `--json` view though if that is primarily what you are using to get this information.

**Comment by allmightyspiff** [comment]
## TODO:
`slcli block volume-list` and `slcli file volume-list` should only trim the notes output if the environment output format is `table`. `JSON` and `RAW` output formats should have the entire note in the listing.

**Comment by dinogg** [comment]
> ## TODO:
> `slcli block volume-list` and `slcli file volume-list` should only trim the notes output if the environment output format is `table`. `JSON` and `RAW` output formats should have the entire note in the listing.

Adding this back for the json output would be perfect!

**Comment by dinogg** [comment]
@allmightyspiff Thank you again!  I just picked up the change and it works like a charm!
