### ISSUE TITLE
Report Bandwidth Pool lists

### ISSUE THREAD

**Issue by rak287** [softlayer/softlayer-python#1575]
We are using pooled bandwidth feature to use consolidated bandwidth in multiple regions. We wanted to sort the report using slcli to pull bandwidth report.

**What are you trying to do?**
i can able to run the report of current usage using 'slcli report bandwidth' 

Usage: slcli report bandwidth [OPTIONS]

  Bandwidth report for every pool/server.

  This reports on the total data transfered for each virtual sever, hardware server
  and bandwidth pool.

Options:
  --start TEXT   datetime in the format 'YYYY-MM-DD' or 'YYYY-MM-DD HH:MM:SS'
  --end TEXT     datetime in the format 'YYYY-MM-DD' or 'YYYY-MM-DD HH:MM:SS'
  --sortby TEXT  Column to sort by  [default: hostname]
  --virtual      Show the all bandwidth summary for each virtual server
  --server      Show the all bandwidth summary for each hardware server
  -h, --help   Show this message and exit.

What feature we need to add ??
If we can get another option added to this feature something like  
   --pool  show the all bandwidth summary for each bandwidth pool (So we dont really need a giant report which take long to run every-time i try to get this report. 

**Screen shots**
I tried to scope this feature something like this on my side to pull it on timely would helpful if this grouping available through slcli

-bash-4.2# slcli report bandwidth |grep -i pool
Generating bandwidth report for 2021-12-21 00:00:00 to 2022-01-20 00:00:00
Calculating for bandwidth pools  [####################################]  100%          
Calculating for hardware  [####################################]  100%          
Calculating for virtual  [####################################]  100%          
pool      Amsterdam               xxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxx    NULL    
pool      Singapore                  xxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxx   NULL    
pool      US-EAST                   xxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxx   NULL    
pool      US-WEST                  xxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxx   NULL  

**Additional context**

**Comment by allmightyspiff** [comment]
@rak287 I have a test branch up with a rough draft of this feature request on https://github.com/softlayer/softlayer-python/tree/issues1575 . If you are able to test it out on your account and let me know of any issues that would be helpful. If not no worries, I just need a few more days to generate some real bandwidth data and I can test on my account.

This issue adds the `--pool` flag to `slcli -v report bandwidth --pool` which will only print out information for the bandwidth pools you have.

It also adds `slcli account bandwidth-pools` which prints out information similar to https://cloud.ibm.com/classic/network/bandwidth/vdr

I'll also add the ability to add/remove/view details of a pool in #1577

**Comment by allmightyspiff** [comment]
`slcli report bandwidth --pools`
![image](https://user-images.githubusercontent.com/7408017/151055495-0955456c-469a-417c-890a-eaf7676420a7.png)

`slcli account bandwidth-pools`
![image](https://user-images.githubusercontent.com/7408017/151055601-0af696e1-7d67-422e-915d-4e996df7f510.png)

**Comment by allmightyspiff** [comment]
@rak287 this feature is now in v5.9.9 which should be available now https://test.pypi.org/project/SoftLayer/
