### ISSUE TITLE
Feature(cmd) needed for fetching volume clone split/move percentage 

### ISSUE THREAD

**Issue by ko101** [softlayer/softlayer-python#1642]
> REMINDER: Never add usernames or apikeys in these issues, as they are public.

**What are you trying to do?**
While volume clone/duplication active transaction, we will needing this feature to fetch the clone split/ move percentage (if its in progress else throw exception) by backend and displaying it to customer.
Jira : [FBLOCK-4521](https://jira.softlayer.local/browse/FBLOCK-4521)

**Screen shots**
If the functionality you want exists in the portal, please add a screenshot so we have a better idea of what you need.

**Additional context**
There will a sldn exposed API [FBLOCK-4520](https://jira.softlayer.local/browse/FBLOCK-4520) will be there, that's output we should consume by our new slcli cmd to fetch results.

**Comment by allmightyspiff** [comment]
@ko101 Can you let us know the following:

1. What API should we be using?
2. Some information on what the API will return. What errors it will emit,  that sort of thing
3. When will customers want to know this information? What is a volume clone/split/move. I have some assumptions based on their names, but I don't really know what will trigger those actions or anything.
Thanks.

**Comment by ko101** [comment]
1.What API should we be using?
Ans. sldn exposed API - getDuplicateConversionStatus() (https://jira.softlayer.local/browse/FBLOCK-4520)
2.Some information on what the API will return. What errors it will emit, that sort of thing
Ans. Api will return a container class (Object)
3.When will customers want to know this information? What is a volume clone/split/move. I have some assumptions based on their names, but I don't really know what will trigger those actions or anything.
Thanks.
Ans. Customer needing this for fetching of duplicate split/move conversion status. clone/split/move are feature of volume.

PR for above issue - https://github.com/softlayer/softlayer-python/pull/1655

**Comment by ko101** [comment]
Please note that above API is not released yet to production
