### ISSUE TITLE
Static Subnets and RIR Registration

### ISSUE THREAD

**Issue by beittenc** [softlayer/softlayer-python#166]
This is to track the remaining work that needs to be done from #56.

Currently static subnets cannot be created, so that needs to be added. We also need to determine how to best support RIR registration functionality.

**Comment by sudorandom** [comment]
Updating RIR information is such a rare action that it doesn't seem needed for the CLI.

Ordering static subnets does seem very useful and a common use-case.

**Comment by sudorandom** [comment]
Closing this until there is more interest.
