### ISSUE TITLE
'option create-options in commands hardware and dedicatedhost' command is displaying an error message

### ISSUE THREAD

**Issue by BrianSantivanez** [softlayer/softlayer-python#1701]
> Reminder: No username or APIkeys should be added to these issues, as they are public.

**Describe the bug**
'slcli hardware create-options' command is displaying an error message instead to display the options to create a hardware

**Expected behavior**
The command should not display and error and should display the options to create a hardware

**Screenshots**
![image](https://user-images.githubusercontent.com/78806346/179859475-cfdb58e9-8053-4e38-8285-8f308180d50d.png)

**Version**
![image](https://user-images.githubusercontent.com/78806346/179859540-c06bf2fb-4d6f-4aec-b375-71e3e25473e9.png)

**Comment by edsonarios** [comment]
Find the same error in other command
![image](https://user-images.githubusercontent.com/43519769/180030475-7ceedae6-aca2-4e1b-9ad4-fecb8cb15906.png)
