### ISSUE TITLE
Rich Text colors things with a `-` in them in the help text

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#1733]
![image](https://user-images.githubusercontent.com/7408017/184696040-6f2590d7-1318-4ab1-9c2b-ae3b7afae1c5.png)

**Comment by edsonarios** [comment]
This behavior also is found in the long help text
![image](https://user-images.githubusercontent.com/43519769/193313927-f5402736-23c1-4ef1-8973-d5067a85d542.png)
