### ISSUE TITLE
Warning with urllib3 1.26.13

### ISSUE THREAD

**Issue by hasan4791** [softlayer/softlayer-python#1809]
Hello team,

With the latest urllib3 version, slcli is throwing the below warning.
```
slcli --version
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Current: slcli (SoftLayer Command-line) v6.1.3
Latest:  slcli (SoftLayer Command-line) v6.1.3
```

**Comment by caberos** [comment]
Please a update the 'request' library as show link
[requestError](https://stackoverflow.com/questions/73199376/requestsdependencywarning-urllib3-1-26-11-or-chardet-3-0-4-doesnt-match-a)

**Comment by hasan4791** [comment]
Ufff, my bad. Even we had selenium running and upgrading requests to 2.28.1 cleared the warning.
