### ISSUE TITLE
BUG:  SoftLayer_Network_Storage_Backup_Evault_Version6 backupJobDetails mask is not working

### ISSUE THREAD

**Issue by figueira-israel** [softlayer/softlayer-python#1849]
We've been using this api call for quite some time, but since 01/27/23 we started getting the error below

"error": "Internal Error",
"code": "SoftLayer_Exception_Public"

https://api.softlayer.com/rest/v3/SoftLayer_Account/getEvaultNetworkStorage?objectMask=mask(SoftLayer_Network_Storage_Backup_Evault_Version6)[virtualGuest,hardware,backupJobDetails]

if you remove the backupJobDetails from the mask it works, was something changed in the api? If so is there another way to get the evault backup job details?

![image](https://user-images.githubusercontent.com/33461144/216431535-f7cf65df-4dc3-4527-9d9a-128ef5e9e314.png)

**Comment by allmightyspiff** [comment]
Since this bug isn't with the softlayer-python client I'll continue this conversation with you on Slack.
