### ISSUE TITLE
Update command `slcli block snapshot-order`

### ISSUE THREAD

**Issue by edsonarios** [softlayer/softlayer-python#1856]
Add new flag: --iops
Update flag, change name: --capacity to --size

**Comment by ramkishor-ch** [comment]
Hi @allmightyspiff,

I have checked that --iops and --size flags are added in this pull request #1858.

Can you please review  and close it.

Please find the screen shot.

Screen Shot:
<img width="1271" alt="Screenshot 2023-07-04 at 7 23 19 PM" src="https://github.com/softlayer/softlayer-python/assets/125332006/268152d2-2083-44b1-89ef-da3d57daec07">


Thanks,
Ramkishor Chaladi.
