### ISSUE TITLE
slcli event-log get - fail due to permission issue

### ISSUE THREAD

**Issue by twoerthle** [softlayer/softlayer-python#1905]
```
> slcli event-log get -l -1 --metadata -d 04/12/2023
Event, Object, Type, Date, Username, Metadata
SoftLayerAPIError(SoftLayer_Exception_PermissionDenied): You do not have permission to access this user. 
````

**Describe the bug**
Receiving the error `SoftLayerAPIError(SoftLayer_Exception_PermissionDenied): You do not have permission to access this user.` when running the `event-log get` slcli command. This was previously reported via https://github.com/softlayer/softlayer-python/pull/1887 but the issue seems to persist @caberos. Submitting this as IBM Cloud support requested further issues be reported here.

**Expected behavior**
IBM Cloud audit/event log Results should be returned - https://softlayer-python.readthedocs.io/en/latest/cli/event_log/

**Screenshots**
N/A

**Version**
```
>  slcli --version
Current: slcli (SoftLayer Command-line) v6.1.6
Latest:  slcli (SoftLayer Command-line) v6.1.6
```

**Comment by caberos** [comment]
Please, could you review your  permissions, is possible you has not the permissions need to used some requests, please could you review these pages. 
[permission](https://sldn.softlayer.com/article/permission-enforcement-softlayer-api/)
[authentication](https://sldn.softlayer.com/article/authenticating-softlayer-api/)
[access error](https://sldn.softlayer.com/article/exception-handling-softlayer-api/)

**Comment by allmightyspiff** [comment]
@twoerthle I'll take a look at this issue.
