### ISSUE TITLE
Enhance CCI DNS sync to update AAAA records

### ISSUE THREAD

**Issue by briancline** [softlayer/softlayer-python#192]
Easy low-hanging fruit for the next milestone...

For folks with IPv6 addresses on their CCIs, having `sl cci dns sync` perform a sync of the AAAA record would be a useful addition as well.

Would be as simple as adding another `--AAAA` option to the existing command.

This would not include the full /64 block of addresses that is provided to them if they select at order time, only the *single* IPv6 address we provide to them if they chose it.

**Comment by underscorephil** [comment]
@sudorandom @briancline: you can get the v6 address for a server with frontendNetworkComponents.primaryVersion6IpAddressRecord.

EX: https://gist.github.com/underscorephil/75709f051f4356f111e6

**Comment by allmightyspiff** [comment]
https://github.com/softlayer/softlayer-python/pull/661

**Comment by sudorandom** [comment]
Closed via #661
