### ISSUE TITLE
`slcli ticket list` has imposed a `limit=100` restriction

### ISSUE THREAD

**Issue by pauljnightingale** [softlayer/softlayer-python#2049]
> Reminder: No username or APIkeys should be added to these issues, as they are public.

**Describe the bug**
`slcli ticket list` has imposed a `limit=100` restriction
This restriction is fine as a default but there is no customer option to provide an higher value, such as `slcli ticket detail N --count  N`
https://github.com/softlayer/softlayer-python/commit/ac2d7cfb8c89026d95f82feacae2c87a32591f71#diff-a938c2e33e2d945a88ce194087c36e2e39f5abfecbed0c79c984e5fab70cf5ec

**Expected behavior**
This is a change of behaviour and can result in an incomplete list being returned

Noting, this is inconsistent with `ibmcloud sl ticket list` that returns the full list 

**Screenshots**

**Version**
Include the output of `slcli --version`
```
slcli --version
Current: slcli (SoftLayer Command-line) v6.1.7
Latest:  slcli (SoftLayer Command-line) v6.1.7
```

**Comment by allmightyspiff** [comment]
@JayasilanJibm Can you take a look at this one. thanks
