### ISSUE TITLE
Remove requirements in description of `volume-modify` commands

### ISSUE THREAD

**Issue by vickmuir** [softlayer/softlayer-python#2107]
**Describe the bug**
The limitations around the 0.25 tier of Endurance and 0.3 IOPS/GB performance level of Performance storage have been resolved by replacing the HDD storage with SSDs in all our DCs. So when our customers want to modify the IOPS of their storage volumes, they can do so without the previous restrictions.

The description of the following commands contains requirements that can be removed:
- `ibmcloud sl file volume-modify`
- `ibmcloud sl block volume-modify`
- `slcli file volume-modify`
- `slcli block volume-modify`

**Expected behavior**
CLI allows the customers to increase their IOPS without increasing the volume size even if they originally provisioned their volume in the lowest IOPS tier. This issue is created to update the description and remove the requirements that are presented when the customer uses `-help` to see how the command is to be used.

**Screenshots**

<img width="1019" alt="Screenshot 2023-10-05 at 12 54 58 PM" src="https://github.com/softlayer/softlayer-python/assets/28069378/6324f492-61c4-49ba-83ec-9e20e03b0f7f">
<img width="1000" alt="Screenshot 2023-10-05 at 12 55 17 PM" src="https://github.com/softlayer/softlayer-python/assets/28069378/aabb9562-c340-42a7-8d0a-41f74dc91ece">

**Version**
Include the output of `slcli --version`

**Comment by allmightyspiff** [comment]
Updated block|file volume-modify help message
![image](https://github.com/softlayer/softlayer-python/assets/7408017/3aac1779-bc47-49b5-b191-5371d22fbd41)
