### ISSUE TITLE
Allow API Key to Be Passed as a Command-Line Argument in `slcli`

### ISSUE THREAD

**Issue by mohammedTalukder** [softlayer/softlayer-python#2183]
> REMINDER: Never add usernames or apikeys in these issues, as they are public.

**What are you trying to do?**
Hi, I'm currently using `slcli` with a config file, so the credentials and endpoint are read from there. However, I'm wondering if it's possible to pass the credentials at runtime, such as:

```
slcli --apikey xxxxx ...
```

This would be useful because we manage multiple accounts, and we frequently change API keys. Our team uses 1Password to manage secrets, and our internal tool integrates with it. 

If the `--apikey` parameter could be supplied directly, we could retrieve the API key from 1Password like this:

```
slcli --apikey $(op item get ITEM --vault VAULT_NAME --fields FIELD)
```

That would make life a little simpler :-)

**Comment by mohammedTalukder** [comment]
I just discovered this, 
```
SL_API_KEY=$(op item get ibm_cloud --vault utilitarian --fields cldtibmc_api_key)
$ export SL_API_KEY
$ slcli --really hw detail ...
```
so, that's an alternative

**Comment by allmightyspiff** [comment]
Yeah, `SL_API_KEY` would be the way to do that, having a CLI option isn't ideal since it would put your api key into the bash_history.

If you have any other suggestions though please let me know, always happy to hear them.
