### ISSUE TITLE
Manager Examples in Documentation

### ISSUE THREAD

**Issue by sudorandom** [softlayer/softlayer-python#258]
Pretty much every manager needs at least one example of how to use it. This issue is to track the work done on this. The first manager done should be the CCI Manager.

**Comment by allmightyspiff** [comment]
@sudorandom  + @underscorephil 
https://github.com/allmightyspiff/softlayer-python/commit/14b7f4dc68193dbfbc3c671d29781888a74639b1

Let me know what you think about those examples before I start doing more of them.

**Comment by sudorandom** [comment]
One issue has been completed for this. I'm going to close this just to remove noise.
