### ISSUE TITLE
Event Management Support

### ISSUE THREAD

**Issue by dbaggett** [softlayer/softlayer-python#261]
The event management system (EMS) is a relatively new system designed to notify customers about ongoing outages and maintenance's that may be affecting their services. This system is a targeted system and is designed to deliver notifications in a timely manner. Currently, users can view notifications for ongoing events - affecting their service(s) - in the customer portals.

This issue will provide CLI support for viewing service affecting events and list the service(s) affected (hopefully none - ever!).

http://blog.softlayer.com/2013/improving-communications-for-customer-affecting-events/

**Comment by sudorandom** [comment]
I'm guessing this is abandoned. I'm going to close this until there's activity or push to have this implemented.
