### ISSUE TITLE
Review help/doc text for consistent voice

### ISSUE THREAD

**Issue by briancline** [softlayer/softlayer-python#415]
A lot of our CLI help text and inline CLI and API documentation has been written and revised by a number of gracious contributors, so it's natural that not all of it is in the same voice. There could also be some subtle inaccuracies.

A full review would be ideal for the 4.0.0 release.

**Comment by sudorandom** [comment]
Closing as "too vague to feasibly do". I've found that it's much easier to get started with issues which have at least some specifics.

**Comment by briancline** [comment]
But it involves reading...how specific does this need to be?

**Comment by sudorandom** [comment]
@briancline It should probably be broken up per-page.... And maybe start off with some general rules regarding the consistency of the voice: Past/present tense? First/third person? Are occasional jokes okay?
