### ISSUE TITLE
Rename sl Command

### ISSUE THREAD

**Issue by sudorandom** [softlayer/softlayer-python#425]
The debian package has a patch which renames `sl` to `SL`. This is because a very important program is already using `sl` [0]. Therefore, we should probably use a different name.

Here are my suggestions in order of my preference.

 * slcli
 * sl-cli
 * sl-cmd
 * softlayer

The old name will probably hang around just to inform users to use the new command.

[0] - http://www.cyberciti.biz/tips/displays-animations-when-accidentally-you-type-sl-instead-of-ls.html

**Comment by allmightyspiff** [comment]
+1 slcli

**Comment by sudorandom** [comment]
Resolved via #504
