### ISSUE TITLE
CLI to make arbitrary API calls

### ISSUE THREAD

**Issue by sudorandom** [softlayer/softlayer-python#439]
I've created a version of this already and it has been really neat. The idea is that this would make it easy to experiment with the API. I've found myself opening up a python shell and running the 3 lines it takes before actually running the API call I'm curious about at the time. This would avoid that boilerplate.

``` bash
$ sl call-api Account getVirtualGuests --mask=id,hostname --limit=20
.... (table including the id and hostname properties)....
```

**Comment by MiguelHigorre** [comment]
Hello,

Is there an ETA to release v4.0.0?

Thanks in advance,
