### ISSUE TITLE
Consistent Performance volumes not in iscsi list

### ISSUE THREAD

**Issue by mjfork** [softlayer/softlayer-python#456]
Consistent Performance volumes are not shown in the iscsi list command.  Doing an iscsi detail with an ID obtained from the portal works as expected.

**Comment by Neetuj** [comment]
@underscorephil  @sudorandom  should consistent perfomance(file storage, block storage)  volumes how up in iscsi ? or be in a seperate command line ?

**Comment by underscorephil** [comment]
@Neetuj 

If both the legacy iSCSI product and the new Consistent Performance offering have the same feature set, I see no harm in having them interacted with in the same manner through the CLI. If the features differ though, it may be good to separate them out.

**Comment by mjfork** [comment]
They are separate product lines and should probably be separated.

Michael

-------------------------------------------------
Michael Fork
Storage Product Manager
SoftLayer, an IBM Company

**Comment by sudorandom** [comment]
This has been completed in another issue. This will be released in v5.2.0
