### ISSUE TITLE
Version 4 Notes

### ISSUE THREAD

**Issue by sudorandom** [softlayer/softlayer-python#469]
This issue is a place to track the changes for version 4 and will eventually feed into the changelog.

Because there are many changes between version 3 and version 4, it is strongly recommend to pin the version of the SoftLayer python bindings as soon as you can in order to prevent unintentional breakage when upgrading. To keep yourself on version 3, you can use this directive: `softlayer>=3,<4`. That can be used with pip (`pip install softlayer>=3,<4`), requirements in your setup.py and/or in your requirements.txt file.

**Programmatic Interfaces:**
* The hardware manager has a significant update to how place_order() works. It will now only support the fast server provisioning package which has presets for options like CPU, Memory and disk.
* The client transport is now pluggable. If you want to add extra logging or accounting, you can now subclass or wrap `softlayer.transports.XmlRpcTransport` in order to do so. A good example of that is done with `softlayer.transports.TimingTransport`.
* Removed deprecated `SoftLayer.CCIManager` alias.
* Adds virtual server rescue command to SoftLayer.VSManager
* Adds ability to import virtual images from a given URI. The API only supports importing from a swift account using `swift://`.

**Command-line Client:**
* The command is renamed from `sl` to `slcli` to avoid package conflicts.
* Global options now need to be specified right after the slcli command. For example, you would now use `sl --format=raw vs list` over `sl vs list --format=raw``. This is a change for the following options:
 * `--format`
 * `-c` or `--config`
 * `--debug`
 * `--proxy`
 * `-y` or `--really`
 * `--version`
* A `--fixtures` global flag was added to pull from fixture data instead of the API. This is useful for discovery, demonstration and testing purposes.
* A `--verbose` or `-v` flag was added to eventually replace `--debug`. To make a command more verbose, simply add more `-v` flags. For example `sl -vvv vs list` will be the most verbose and show everything down to request/response tracing.
* Significant changes were done to the implementation. Docopt was dropped in favor of [click](http://click.pocoo.org/). Therefore, some subtle differences which aren't documented here may exist.
* Credentials can now be requested using `sl vs credentials <identifier>`, `sl hardware credentials <identifier>` and `sl nas credentials <identifier>` for virtual servers, hardware servers and NAS accounts respectively.
* Adds virtual server rescue command, `sl vs rescue <identifier>`
* Adds ability to import virtual images from a given URI. The API only supports importing from a swift account using `swift://`.

**Comment by briancline** [comment]
@underscorephil / @sudorandom / @jasonjohnson -- You guys see any reason not to go ahead and cut a 4.0.0 release?

If no objections and we're happy with what's in master constituting v4.0.0, I'll go ahead and get this party started.

**Comment by sudorandom** [comment]
@briancline #509 with the version bump and patch notes is the last thing.

**Comment by briancline** [comment]
Noting here for the others to reference... #510 also merged due to some issues found in testing for this release. Those are getting documented in #511 for the time being (feel free to break up into multiple issues if necessary).
