### ISSUE TITLE
The "sl vs capture" command raises an exception when try to capture all disks from a Windows VS with associated CDRom drives.

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-python#474]
The "sl vs capture serverId --name IMAGENAME arcsrv001 --all" command raises the following exception when try to capture all disks from a Windows  VS which has associated CDRom drives.

SoftLayerAPIError(SoftLayer_Exception_Public): Invalid block device supplied. Please be sure to not include the block device for a swap disk.

The "sl vs capture" command needs to be improved in order to exclude CDRom drives.

**Comment by sudorandom** [comment]
This has been completed a while ago.
