### ISSUE TITLE
sl command Error??

### ISSUE THREAD

**Issue by naoki4277** [softlayer/softlayer-python#475]
Hi, I am installing Python CLI tools, but I cant run sl command with following error..

# sl
Traceback (most recent call last):
  File "/usr/bin/sl", line 7, in <module>
    from SoftLayer.CLI.core import main
  File "/usr/lib/python2.6/site-packages/SoftLayer/CLI/core.py", line 56, in <module>
    from SoftLayer.CLI import environment
  File "/usr/lib/python2.6/site-packages/SoftLayer/CLI/environment.py", line 9, in <module>
    import importlib
ImportError: No module named importlib

if anyone can resolve this issue, please let me know,,

NS

**Comment by Neetuj** [comment]
https://github.com/softlayer/softlayer-python/blob/6bca8374a3561a113769b2aba3938d19aba071e4/setup.py

if sys.version_info < (2, 7):
REQUIRES.append('importlib')

for python <2.7 it is supposed to get importlib

did you run python setup.py install ? 
Can you used python 2.7 ?

**Comment by sudorandom** [comment]
I'm closing this until there's more information. Feel free to reach out to the `#softlayer` irc channel on freenode.
