### ISSUE TITLE
The "SoftLayer_Billing_Order_Quote::verifyOrder" method fails when try to order a VSI with python client

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-python#476]
When trying to order a virtual server instance using the python client the "SoftLayer_Billing_Order_Quote::verifyOrder" method fails and raises the following exception:

"An invalid price was submitted with this order"

The exception is raised despite it is possible order using the same quote from UI and also using the php client.

To reproduce the issue using python client, run the following python code

import SoftLayer.API
import pprint

apiUsername = 'set-me'
api_key = 'set-me'

quoteId = 123456 

client = SoftLayer.Client(username=apiUsername, api_key=api_key)

order_templates = client['SoftLayer_Billing_Order_Quote'].getRecalculatedOrderContainer(id=quoteId)

order_data = order_templates['orderContainers'][0]
order_data['complexType'] = 'SoftLayer_Container_Product_Order_Virtual_Server'

order_data['quantity'] = 1

order_data['location'] = '154820'
order_data['presetId'] = None
order_data['sshKeys'] =  [{"sshKeyIds":[29106,94198]}]
order_data['provisionScripts'] = ['http://test/example.com/test.sh']
order_data['hardware'] = [{'hostname': 'server01', 'domain': 'example.com'}]
try:
  receipt = client['SoftLayer_Billing_Order_Quote'].verifyOrder(order_data, id=quoteId)
  pprint.pprint(receipt)
except SoftLayer.SoftLayerAPIError as e:
    print("error faultCode=%s, faultString=%s"
          % (e.faultCode, e.faultString))
    exit(1)

**Comment by Neetuj** [comment]
check if this helps 
https://github.com/softlayer/softlayer-python/pull/478

**Comment by MiguelHigorre** [comment]
Hello,
It seems to be that the error was raised due this line "order_data['complexType'] = 'SoftLayer_Container_Product_Order_Virtual_Server' " updating it to "order_data['complexType'] = 'SoftLayer_Container_Product_Order_Virtual_Guest'" fixed the problem.

However a new exception message is raised stating that "Invalid data on the order for property: presetId. Invalid preset id: 0", the workaround for that is set 'presetId' to None.

I think this issue can be closed and a new one can be raised to handle the behavior related to 'presetId' if needed.

**Comment by underscorephil** [comment]
Closing, resolved.
