### ISSUE TITLE
The "SoftLayer_Billing_Order_Quote::placeOrder" method fails when try to order a VSI with python client

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-python#477]
When trying to order a virtual server instance using the python client the "SoftLayer_Billing_Order_Quote::placeOrder" method fails and raises the following exception:

"A hostname is missing from the order."

The exception is raised despite valid parameters are set and it is possible order using the same quote from UI and also using the php client.

To reproduce the problem run the below code.

import SoftLayer.API
import pprint

apiUsername = 'set-me'
api_key = 'set-me'

quoteId = 123456

client = SoftLayer.Client(username=apiUsername, api_key=api_key)

order_templates = client['SoftLayer_Billing_Order_Quote'].getRecalculatedOrderContainer(id=quoteId)

order_data = order_templates['orderContainers'][0]
order_data['complexType'] = 'SoftLayer_Container_Product_Order_Virtual_Server'

order_data['quantity'] = 1

order_data['location'] = '154820'
order_data['presetId'] = None
order_data['sshKeys'] = [{"sshKeyIds":[29106,94198]}]
order_data['provisionScripts'] = ['http://test/example.com/test.sh']
order_data['hardware'] = [{'hostname': 'server01', 'domain': 'example.com'}]
try:
receipt = client['SoftLayer_Billing_Order_Quote'].placeOrder(order_data, id=quoteId)
pprint.pprint(receipt)
except SoftLayer.SoftLayerAPIError as e:
print("error faultCode=%s, faultString=%s"
% (e.faultCode, e.faultString))
exit(1)

**Comment by Neetuj** [comment]
check if this helps 
https://github.com/softlayer/softlayer-python/pull/478

**Comment by MiguelHigorre** [comment]
Hello,
It seems to be that the error was raised due this line "order_data['complexType'] = 'SoftLayer_Container_Product_Order_Virtual_Server' " updating it to "order_data['complexType'] = 'SoftLayer_Container_Product_Order_Virtual_Guest'" fixed the problem.

The issue is going to be closed.
