### ISSUE TITLE
Add IPMI Password to server detail

### ISSUE THREAD

**Issue by underscorephil** [softlayer/softlayer-python#480]
When running the server detail command with the --passwords switch the IPMI password should be displayed.

**Comment by Neetuj** [comment]
which command are we talking about ? sl vs detail --password?

**Comment by Neetuj** [comment]
got it its  sl server detail  vmhost11  --passwords

**Comment by Neetuj** [comment]
~/office/softlayer-python (master) > sl server detail vmhost11 --passwords
:..............:......................................:
:         Name : Value                                :
:..............:......................................:
:           id : 28023                                :
:         guid : f4cedd4b-be51-4b70-a23d- :
:     hostname : vm                             :
:       domain : sftl                            :
:         fqdn : vmhost                  :
:       status : ACTIVE                               :
:   datacenter : sea01                                :
:        cores : 4                                    :
:       memory : 4G                                   :
:    public_ip : 1.2.3.4                         :
:   private_ip : 1.2.3.4                        :
:      ipmi_ip : 2.3.4.5                       :
:           os : XenServer                            :
:      created : 2012-10-18T14:16:45-07:00            :
:        owner : klandreth                            :
:        vlans : :.........:........:.......:         :
:              : :   type  : number :   id  :         :
:              : :.........:........:.......:         :
:              : : PRIVATE :  1680  : 71988 :         :
:              : :  PUBLIC :  1744  : 71987 :         :
:              : :.........:........:.......:         :
:        notes : KVM Host                             :
:        users : :..........:..........:              :
:              : : username : password :              :
:              : :..........:..........:              :
:              : :   root   : abcd :              :
:              : :..........:..........:              :
: remote users : :...............:............:       :
:              : : ipmi_username :  password  :       :
:              : :...............:............:       :
:              : :      root     : efgh :       :
:              : :...............:............:       :
:         tags : kvm,sheepdog                         :
:..............:......................................:

**Comment by Neetuj** [comment]
:        users   : :..........:..........:              :
:                   : : username : password :              :
:                   : :..........:..........:              :
:                   : :   root   : ABD :              :
:                   : :..........:..........:              :
: remote users : :...............:............:       :
:                  : : ipmi_username :  password  :       :
:                  : :...............:............:       :
:                  : :      root     : EFGH :       :
:                   : :..........:..........:              :

**Comment by Neetuj** [comment]
#482
