### ISSUE TITLE
ticket creation subject seems wrong

### ISSUE THREAD

**Issue by mzupan** [softlayer/softlayer-python#484]
Maybe I'm not using it right but I have the following

```
    client = SoftLayer.Client()
    mgr = SoftLayer.TicketManager(client)

    #
    # creating ticket now
    t = mgr.create_ticket('Dead Drive', body, subject=1021)
    ticket = t['id']
```

The subject 1021 should be for hardware

```
>>> pprint.pprint(mgr.list_subjects())
[{'id': 1522, 'name': 'API Question'},
 {'id': 1482, 'name': 'Vyatta Question'},
 {'id': 1001, 'name': 'Accounting Request'},
 {'id': 1002, 'name': 'Sales Request'},
 {'id': 1003, 'name': 'Reboots and Console Access'},
 {'id': 1041, 'name': 'DNS Request'},
 {'id': 1021, 'name': 'Hardware Issue'},
```

When the ticket is created it gets put in the sysadmin group in the control panel

**Comment by sudorandom** [comment]
I'm not 100% sure how groups are associated with ticket subjects (if they are at all). Maybe @underscorephil or @allmightyspiff knows or is able to look into this?

**Comment by underscorephil** [comment]
Howdy!

I just tested your code and the ticket was created in the Support group as Hardware Issue - Dead Drive. Could you send me the ticket ID that showed this behavior. Are you able to recreate the issue on your end?

**Comment by sudorandom** [comment]
@mzupan I'm going to close this until there's a way to reproduce this reliably. It might be that someone manually changed the categorization of the ticket after creation... Feel free to re-open if you think this is still an issue.

**Comment by robertkowalski** [comment]
I have the same issue right now

**Comment by robertkowalski** [comment]
@underscorephil ticket id is `26333595`

**Comment by robertkowalski** [comment]
there was no manual change after creation in my case, the issue came up when i tried to assign hardware to the ticket
