### ISSUE TITLE
Promote client.call(service, method) over client[service].method()

### ISSUE THREAD

**Issue by sudorandom** [softlayer/softlayer-python#487]
Adding syntax to make the SLAPI client appear like a dictionary of services only adds needless confusion and syntax which is hard to break up into multiple lines with long service names. For example:
```python
import SoftLayer
client = SoftLayer.Client()
template = client["Virtual_Guest_Block_Device_Template_Group"].getObject(id=12345)
```
That's a really long line. This already exists as a solution to that problem:
```python
template = client.call("Virtual_Guest_Block_Device_Template_Group",
                       "getObject",
                       id=12345)
```
or this
```python
template = client.call(
    "Virtual_Guest_Block_Device_Template_Group",
    "getObject",
    id=12345,
)
```

I propose using `client.call(service, method)` over the `client[service].method()` in documentation and eventually converting all the manager code to using it as the primary method for calling the SLAPI.

1. It's less magic.
2. It's less syntax.
3. It's easier to split into multiple lines without adding additional variables or making the code look awkward.
4. Phil thinks it looks more aesthetically pleasing.

**Comment by underscorephil** [comment]
+1
It is also more aesthetically pleasing.
