### ISSUE TITLE
Custom columns for vs list

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#490]
I often find myself editing the source code everytime I want to display "vs list" differently, there must be a better way :)

![screen shot 2015-02-18 at 2 49 19 pm](https://cloud.githubusercontent.com/assets/7408017/6256401/5b0d5928-b77d-11e4-97e1-43ca1eb16ffc.png)

This will likely apply nicely to hw list too.

I'll be submitting the code in a bit.

**Comment by sudorandom** [comment]
+1 to this idea

**Comment by allmightyspiff** [comment]
https://github.com/allmightyspiff/softlayer-python/commit/011b7fc45a99543a994c8a6d2c2248d984d2484a

^^ what I have so far. 

Some things to consider

1. It might be a good idea to remove the limit  on sortBy options and just check in the code to make sure the selected column is actually going to be displayed.
2. I've kept the old column names, although this is going to give us a lengthy list of if's. Not the worst thing in the world.
3. @underscorephil suggested having the --column actually be an object mask, capable of tapping into new objects. Although that idea might be a bit ambitious for today :)

**Comment by sudorandom** [comment]
@allmightyspiff I made one comment in-line. Regarding your list:

1. That sounds fine. I think it raises an error once our table concept is converted to a pretty table
2. Instead of a bunch of ifs, use a map (dictionary) to look up the nice names to the API names.
3. Look at the 'call-api' command that's in master. It can do this with any API call.
```
sl call-api Account getVirtualGuests --mask='id,hostname'
```

**Comment by allmightyspiff** [comment]
https://github.com/softlayer/softlayer-python/pull/503  is ready to go for this issue.
