### ISSUE TITLE
reboot a server prompting for confirmation

### ISSUE THREAD

**Issue by sandegan** [softlayer/softlayer-python#491]
Hi 
sl vs reboot <IDENTIFIER> prompting for Y/n confirmation. How can I avoid this option.
I want reboot the server from a script without any prompt.

**Comment by sudorandom** [comment]
You can use the `-y` or `--really` flag to confirm confirmation prompts.

**Comment by sandegan** [comment]
Thanks
Kevin

I am getting the error.

[root@oc1132033718 softlayer-softlayer-python-2fef3fd]#
[root@oc1132033718 softlayer-softlayer-python-2fef3fd]# sl vs reboot
8591576d-64ef-40b3-8c6e-e6d1b0372c15 -y
Usage: sl vs reboot [OPTIONS] IDENTIFIER

Error: no such option: -y
[root@oc1132033718 softlayer-softlayer-python-2fef3fd]# sl vs reboot
8591576d-64ef-40b3-8c6e-e6d1b0372c15 --confirm
Usage: sl vs reboot [OPTIONS] IDENTIFIER

Error: no such option: --confirm
[root@oc1132033718 softlayer-softlayer-python-2fef3fd]# s


Regards,

Sandeep Gangadharan
Linux System Administrator
Red Hat Certified Engineer, ITIL V3 Foundation
ITD GD, India
                                                                                    
                                                                                    
                                                                                    
 Mobile: 91-9866-859808 | Phone: 91-40-4457-6849                                    
 E-mail: sandegan@in.ibm.com                                                        
                                                     B4 Survey No 66/1 Raidurga Vil 
                                                               Hyderabad, AP 500032 
                                                                              India 
                                                                                    





From:	Kevin McDonald <notifications@github.com>
To:	softlayer/softlayer-python
            <softlayer-python@noreply.github.com>
Cc:	Sandeep Gangadharan1/India/IBM@IBMIN
Date:	02/19/2015 08:18 PM
Subject:	Re: [softlayer-python] reboot a server prompting for
            confirmation (#491)



You can use the -y or --really flag to confirm confirmation prompts.


—
Reply to this email directly or view it on GitHub.

**Comment by sandegan** [comment]
Thanks Mac

I am getting the below error.

[root@oc1132033718 softlayer-softlayer-python-2fef3fd]# sl vs reboot
8591576d-64ef-40b3-8c6e-e6d1b0372c15 -y
Usage: sl vs reboot [OPTIONS] IDENTIFIER

Error: no such option: -y
[root@oc1132033718 softlayer-softlayer-python-2fef3fd]# sl vs reboot
8591576d-64ef-40b3-8c6e-e6d1b0372c15 --really
Usage: sl vs reboot [OPTIONS] IDENTIFIER

Error: no such option: --really
[root@oc1132033718 softlayer-softlayer-python-2fef3fd]#


Regards,

Sandeep Gangadharan
Linux System Administrator
Red Hat Certified Engineer, ITIL V3 Foundation
ITD GD, India
                                                                                    
                                                                                    
                                                                                    
 Mobile: 91-9866-859808 | Phone: 91-40-4457-6849                                    
 E-mail: sandegan@in.ibm.com                                                        
                                                     B4 Survey No 66/1 Raidurga Vil 
                                                               Hyderabad, AP 500032 
                                                                              India 
                                                                                    





From:	Kevin McDonald <notifications@github.com>
To:	softlayer/softlayer-python
            <softlayer-python@noreply.github.com>
Cc:	Sandeep Gangadharan1/India/IBM@IBMIN
Date:	02/19/2015 08:18 PM
Subject:	Re: [softlayer-python] reboot a server prompting for
            confirmation (#491)



You can use the -y or --really flag to confirm confirmation prompts.


—
Reply to this email directly or view it on GitHub.

**Comment by sudorandom** [comment]
@sandegan Sorry, that's a 'global' option that has to be specified in a specific location. The command would look like this:

```
sl --really vs reboot
8591576d-64ef-40b3-8c6e-e6d1b0372c15
```

To make it that much more confusing, this is one thing that's changed recently and hasn't been semi-released via pypi and only exists in master. The new way of doing this is what I just posted. Your usage of it works with the old/current way. I'm still thinking of a way to make that better. Ideally, you can specify it either way.

**Comment by sudorandom** [comment]
Okay, so this is a bug. What I posted is how it should work. I'll be able to fix this pretty quickly. Thanks.

**Comment by sandegan** [comment]
Thanks Kevin for the quick response.

Still its prompting for the confirmation .
[root@oc1132033718 softlayer-softlayer-python-2fef3fd]# sl --really vs
reboot 8591576d-64ef-40b3-8c6e-e6d1b0372c15
This will reboot the VS with id 8591576d-64ef-40b3-8c6e-e6d1b0372c15.
Continue? [y/N]: :




Regards,

Sandeep Gangadharan
Linux System Administrator
Red Hat Certified Engineer, ITIL V3 Foundation
ITD GD, India
                                                                                    
                                                                                    
                                                                                    
 Mobile: 91-9866-859808 | Phone: 91-40-4457-6849                                    
 E-mail: sandegan@in.ibm.com                                                        
                                                     B4 Survey No 66/1 Raidurga Vil 
                                                               Hyderabad, AP 500032 
                                                                              India 
                                                                                    





From:	Kevin McDonald <notifications@github.com>
To:	softlayer/softlayer-python
            <softlayer-python@noreply.github.com>
Cc:	Sandeep Gangadharan1/India/IBM@IBMIN
Date:	02/19/2015 09:59 PM
Subject:	Re: [softlayer-python] reboot a server prompting for
            confirmation (#491)



Okay, so this is a bug. What I posted is how it should work. I'll be able
to fix this pretty quickly. Thanks.


—
Reply to this email directly or view it on GitHub.

**Comment by sudorandom** [comment]
@sandegan I just merged in the fix to this into master. The command `sl --really vs reboot 8591576d-64ef-40b3-8c6e-e6d1b0372c15` (and several other commands that had the same issue) should properly skip confirmations.

**Comment by sudorandom** [comment]
See http://softlayer-python.readthedocs.org/en/latest/install.html#from-source for source installs to get the updated version.
