### ISSUE TITLE
Unknown argument(s)

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-python#496]
The "Unknow argument(s)" message is raised when try the "sl vs create --hostname=example --domain=softlayer.com --cpu 2 --memory 1024 -o UBUNTU_14_64 --datacenter=sjc01 --billing=hourly" command and the cause seems to be "--billing=hourly" option as a workaround I changed it by "--hourly" and the command worked

**Comment by sudorandom** [comment]
Based on the title, I'm guessing your running into something that's changed with the CLI in version for.

Read https://github.com/softlayer/softlayer-python/issues/469, the second item under "Command-line Client".
