### ISSUE TITLE
Dead link on getting-started

### ISSUE THREAD

**Issue by TiloGit** [softlayer/softlayer-python#500]
On https://softlayer.github.io/softlayer-python/getting-started/

Text: 
See user scenarios and usage examples for creating and working with virtual servers

links to https://softlayer.github.io/softlayer-python/usage
should be: https://softlayer.github.io/softlayer-python/examples/  i guess

**Comment by sudorandom** [comment]
https://softlayer.github.io/softlayer-python now just re-directs to the auto-generated docs
