### ISSUE TITLE
Unable to create vs with tags

### ISSUE THREAD

**Issue by rhodgin** [softlayer/softlayer-python#501]
I'm no longer able to create vs servers with tags from the command line. The help information lists the input as:
``` -g --tag=TAG           Comma list of tags to set ```
but when that is used, the following error is generated:
```
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/core.py", line 199, in main
    data = runnable.execute(command_args)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/CLI/modules/vs.py", line 462, in execute
    result = vsi.create_instance(**data)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/managers/vs.py", line 462, in create_instance
    inst = self.guest.createObject(self._generate_create_dict(**kwargs))
TypeError: _generate_create_dict() got an unexpected keyword argument 'tag'
```
The code makes it seem like tags is the correct input parameter but when that is attempted the call fails during initial validation:
```usage: sl vs create [--disk=SIZE...] [--key=KEY...] [options] ```

**Comment by underscorephil** [comment]
Howdy!

What version of softlayer-python are you running? Could you post the whole command?

**Comment by rhodgin** [comment]
Hi, 
The version is v3.3.1. 
The full command that generates the error is:
```sl vs create --cpu=1 --domain=test.sftlayer.com --memory=1024 --os=CENTOS_LATEST_64 --hourly --disk=25 --tag=testtag --hostname=test1 --datacenter=sjc01```

**Comment by allmightyspiff** [comment]
I was able to reproduce this on centos with a fresh install of Softlayer

```bash
easy_install softlayer
sl config setup
sl vs create --cpu=1 --domain=cgallo.com --memory=1024 --os=CENTOS_LATEST_64 --hourly --disk=25 --tag=testtag --hostname=cgallo-test1 --datacenter=sjc01
```

This problem isn't present in the current master, which seems to only be version [v3.3.0](https://github.com/softlayer/softlayer-python/blob/master/setup.py#L37) for some reason.

![screen shot 2015-03-11 at 11 02 45 am](https://cloud.githubusercontent.com/assets/7408017/6600536/2980eb42-c7de-11e4-9fbc-9ea266082fe2.png)

@sudorandom any chance we can the sl stuff on pypi.python.org updated?

**Comment by sudorandom** [comment]
@allmightyspiff yep, I'm waiting on the last issues of 4.0 to be finished. See the v4.0 milestone: https://github.com/softlayer/softlayer-python/milestones/v4.0.0. I set a deadline so it won't stall anymore.
