### ISSUE TITLE
Modify Virtual Server maintenance slot timezone issue

### ISSUE THREAD

**Issue by allezalps** [softlayer/softlayer-python#505]
Using the following code to modify a virtual server...

```
  # Get SL Client
  client = SoftLayer.Client()

  ...

  # Modify instance
  mgr = SoftLayer.VSManager(client)
  result = mgr.upgrade('xxxxxxxx', cpus='2', memory='2')
```

It works, however it takes 6 hours to perform the upgrade! This seems to be timezone related, as the ticket which is raised shows:

```
Maintenance Start Date: 2015-03-06 13:23:33 (America/Chicago)
```

whereas I raised it at 13:23:33 GMT (my local time), and 13:23:33 Chicago time will be 6 hours later.

The timezones of the master account and the submitter are definitely set to GMT in the portal.

If I edit the vs.py manager script, and change the following at line 631...

```
order['properties'] = [{'name': 'MAINTENANCE_WINDOW',
  'value': str(datetime.datetime.now() - datetime.timedelta(hours=6))}]
```
...then the modify submits immediately (ie. I ask for GMT-6 hours, or Chicago time)

Could you please provide a fix or a workaround? (Or am I just doing something stupid?!!)

(I initially raised this in the SoftLayer Customer Forums, and was asked to raise it here).

**Comment by sudorandom** [comment]
No, you're not doing anything stupid. It sounds like you are running into an issue that's fixed in #493. The fix is currently in the master branch, but hasn't been pushed up to pypi as a release yet.

Is it possible to test with master to see if this fixes the issue for you?

**Comment by allezalps** [comment]
I've just tested with master and it works!! Thank you very much, I look forward to the next release!

**Comment by sudorandom** [comment]
FYI, we hope to have the next release around March 25th: https://github.com/softlayer/softlayer-python/milestones.
