### ISSUE TITLE
The SoftLayer_Ticket::addAttachedFile method fails when tried to attach images

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-python#506]
The SoftLayer_Ticket::addAttachedFile method fails when tried to attach images, the following message is raised
SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Ticket): No valid authentication headers found.

Requirements:
Python 2.6 or 2.7
SoftLayer API python client (3.3.1) 

It seems to be a problem related to Python 2 since using Python 3 or higher the SoftLayer_Ticket::addAttachedFile method works.

The problem is reproduced with the following code

------------------------------------
import SoftLayer
import pprint

apiUsername = 'set-me'
api_key = 'set-me'

apiUsername = 'set-me'
api_key = 'set-me'
ticket_id = set-me
client = SoftLayer.Client(username= apiUsername,api_key=api_key)

f = open('/path/to/image.png', 'rb')
filecontents = f.read()
attachedFile = { 'data': filecontents, 'filename': 'image.png'}
result = client['Ticket'].addAttachedFile(attachedFile, id=ticket_id)
pprint.pprint(result)

-------------------------------------

Here is the traceback for the Python issue.

Traceback (most recent call last):
  File "addAttachedFile.py", line 24, in <module>
    result = client['Ticket'].addAttachedFile(attachedFile, id=13410275)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/API.py", line 351, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/API.py", line 319, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/API.py", line 184, in call
    return transports.make_xml_rpc_api_call(request)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/transports.py", line 137, in make_xml_rpc_api_call
    ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Ticket): No valid authentication headers found.

**Comment by gordonjm** [comment]
I'very been investigating this issue and have seen that the authentication header is constructed, and is part of the payload delivered with the request. However I do not yet understand why this exception is thrown when a Python 2 interpreter is used.

**Comment by gordonjm** [comment]
I believe I have found the issue. In Python 3 it looks like xmlrpc_client.dumps(...) automatically performs base64 encoding on the image data. However in Python 2 we must explicity perform the encoding before forming the payload. I will make the necessary changes and submit a pull request.
