### ISSUE TITLE
Re-merge and improve billing code

### ISSUE THREAD

**Issue by briancline** [softlayer/softlayer-python#511]
Basically a reversal of the reversal: #510

But with fixes. Currently these issues are known with `sl billing list`:
* SLAPI calls take an extremely long time on some accounts, causing command to seemingly hang
* Running without a start/end date on some accounts can yield `ValueError: invalid literal for float(): 0159.80234159.80234`
* Running with a recent start date on some accounts can yield `ValueError: invalid literal for float(): 0159.80234159.80234`
* Reported costs sometimes report fractional cents (i.e., `247.312`) -- should be USD-formatted
* Documentation/help should explicitly note that reported costs are in USD
* Reported costs should be right-aligned in the CLI output
* Piped output doesn't include `-` for empty values, resulting in differing field indices and field counts when parsing via awk/cut/etc.

**Comment by sudorandom** [comment]
Closing this issue until there's more internal sponsorship.
