### ISSUE TITLE
sl ticket detail encode/character maps to <undefined>

### ISSUE THREAD

**Issue by TiloGit** [softlayer/softlayer-python#512]
try to get details of tickets but one has issue with encode:

see here detail info (detail of simple MONITORING works)
---------------------------------------------------------
C:\Tools\Python34\Scripts>python -m pip freeze
docopt==0.6.1
prettytable==0.7.2
requests==2.5.3
six==1.9.0
SoftLayer==3.3.1
---------------------------------------------------------
C:\Tools\Python34\Scripts>sl ticket detail 1751xxxx
:..............:...................................................................................:
:         Name : Value                                                                             :
:..............:...................................................................................:
:           id : 1751xxxx                                                                          :
:        title : MONITORING: Network Monitor Alert                                                 :
: assignedUser : Removed REMOVED                                                                  :
:   createDate : 2015-03-26T12:20:20-08:00                                                         :
: lastEditDate : 2015-03-26T14:18:34-08:00                                                         :
 :    Update 1 : The Automated Monitoring System has detected a service failure on Cloud Instance
  :            : removed.removed.com beginning at 2015-03-26 15:16:06 CDT  This alert has been
              :: generated by our Automated Notification System. This ticket will be
   :           : automatically updated by the system until event resolution.  This alert is not
         :     : being viewed or tracked by support personnel. If you need hands and eyes
       :       : assistance, please contact support or open a new trouble ticket inside the
  :            : customer management portal.  If you want to upgrade your service to include NOC
  :            : response, please contact sales through the customer management portal.  Service
:              : issue: SERVICE PING failed for 169.53.xxx.xx at 2015-03-26 15:16:06 CDT           :
         :te 2 : The following users have received automated notifications regarding this
:              : failure: EMAIL: REMOVED@REMOVED.com                                            :
        :ate 3 : UPDATE (2015-03-26 15:21:06 CDT):  Service Issue: SERVICE PING failed for
:              : 169.53.xxx.xx                                                                     :
         :te 4 : The following users have received automated notifications regarding this
:              : failure: EMAIL: REMOVED@REMOVED.com                                            :
        :ate 5 : UPDATE (2015-03-26 15:27:03 CDT):  Service Issue: SERVICE PING failed for
:              : 169.53.xx.xx                                                                     :
        :ate 6 : UPDATE (2015-03-26 15:31:07 CDT):  Service Issue: SERVICE PING failed for
:              : 169.53.xxx.xx                                                                     :
        :ate 7 : UPDATE (2015-03-26 15:36:57 CDT):  Service Issue: SERVICE PING failed for
:              : 169.53.xxx.xx                                                                     :
        :ate 8 : UPDATE (2015-03-26 15:41:04 CDT):  Service Issue: SERVICE PING failed for
:              : 169.53.xxx.xx                                                                     :
        :ate 9 : UPDATE (2015-03-26 15:47:03 CDT):  Service Issue: SERVICE PING failed for
:              : 169.53.xxx.xx                                                                     :
        :te 10 : UPDATE (2015-03-26 15:51:08 CDT):  Service Issue: SERVICE PING failed for
:              : 169.53.xxx.xx                                                                     :
:..............:...................................................................................:

C:\Tools\Python34\Scripts>sl ticket detail 1761xxxx
An unexpected error has occured:
Traceback (most recent call last):
  File "C:\Tools\Python34\lib\site-packages\SoftLayer\CLI\core.py", line 207, in main
    env.out(output)
  File "C:\Tools\Python34\lib\site-packages\SoftLayer\CLI\environment.py", line 81, in out
    self.stdout.write(output)
  File "C:\Tools\Python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1146-1147: character maps to <undefined>

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

**Comment by sudorandom** [comment]
Interesting. Could you try viewing this same ticket with the version from the master branch? Brief instructions on how to do this are available here: http://softlayer-python.readthedocs.org/en/latest/install.html#from-source

**Comment by TiloGit** [comment]
update to latest (softlayer-softlayer-python-v3.3.0-177-g05fa173.zip)
-----------------------------
C:\Tools\Python34\Scripts>python -m pip freeze
click==4.0
docopt==0.6.1
prettytable==0.7.2
requests==2.6.0
six==1.9.0
softlayer==4.0.0
-----------------------------

but same

-----------------------------
C:\Tools\Python34\Scripts>slcli ticket detail 1761xxxx
An unexpected error has occured:
Traceback (most recent call last):
  File "C:\Tools\Python34\lib\site-packages\SoftLayer\CLI\core.py", line 207, in main
    env.out(output)
  File "C:\Tools\Python34\lib\site-packages\SoftLayer\CLI\environment.py", line 81, in out
    self.stdout.write(output)
  File "C:\Tools\Python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1146-1147: character maps to <undefined>

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues
-----------------------------

**Comment by TiloGit** [comment]
if you shoot me your SL company email I can email you the ticket number for you to test.

**Comment by sudorandom** [comment]
Sure thing. My SL email is kmcdonald@softlayer.com

**Comment by TiloGit** [comment]
removed and reinstalled latest sl now

---------------------------------------------------

C:\Tools\Python34\Scripts>slcli ticket detail 1761xxxx
An unexpected error has occured:
Traceback (most recent call last):
  File "C:\Tools\Python34\lib\site-packages\softlayer-4.0.0-py3.4.egg\SoftLayer\CLI\core.py", line 177, in main
    cli.main()
  File "C:\Tools\Python34\lib\site-packages\click-4.0-py3.4.egg\click\core.py", line 644, in main
    rv = self.invoke(ctx)
  File "C:\Tools\Python34\lib\site-packages\click-4.0-py3.4.egg\click\core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Tools\Python34\lib\site-packages\click-4.0-py3.4.egg\click\core.py", line 959, in _process_result
    **ctx.params)
  File "C:\Tools\Python34\lib\site-packages\click-4.0-py3.4.egg\click\core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "C:\Tools\Python34\lib\site-packages\softlayer-4.0.0-py3.4.egg\SoftLayer\CLI\core.py", line 161, in output_result
    env.out(output)
  File "C:\Tools\Python34\lib\site-packages\softlayer-4.0.0-py3.4.egg\SoftLayer\CLI\environment.py", line 37, in out
    click.echo(output, nl=newline)
  File "C:\Tools\Python34\lib\site-packages\click-4.0-py3.4.egg\click\utils.py", line 293, in echo
    file.write(message)
  File "C:\Tools\Python34\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1410-1411: character maps to <undefined>

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

C:\Tools\Python34\Scripts>

**Comment by sudorandom** [comment]
I'm not sure where this issue left off. I remember that this resulted in a general fix but it was apparently never tied back to this issue. Can you check and see if this issue still persists? I will close this issue until you confirm. Feel free to re-open it.
