### ISSUE TITLE
enableSnapshots method not working

### ISSUE THREAD

**Issue by waltari2001** [softlayer/softlayer-python#521]
Hi,

I'm trying to enable HOURLY/DAILY/WEEKLY snapshots using slcli as follows:

slcli call-api Network_Storage enableSnapshots --id=XXXXXX --retentionCount=3 --scheduleType=HOURLY --minute=59
Error: no such option: --retentionCount

According to the WSDL all these parameters are required.

Thanks,

Sadek

**Comment by sudorandom** [comment]
I'm afraid call-api doesn't yet support API methods with arguments. This can serve as the issue to track the addition of that feature.
