### ISSUE TITLE
'slcli metadata tags' command fails

### ISSUE THREAD

**Issue by MiguelHigorre** [softlayer/softlayer-python#525]
The 'slcli metadata tags' command fails, the following exception is raised when debug is set:

slcli -vvv metadata tags
=== REQUEST ===
https://api.service.softlayer.com/rest/v3.1/SoftLayer_Resource_Metadata/Tags/None.json
{'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate, compress', 'Accept': '*/*', 'User-Agent': 'softlayer-python/v4.0.0'}
Starting new HTTPS connection (1): api.service.softlayer.com
Setting read timeout to 5
"GET /rest/v3.1/SoftLayer_Resource_Metadata/Tags/None.json HTTP/1.1" 404 70
=== RESPONSE ===
CaseInsensitiveDict({'x-client-ip': '192.168.67.116', 'content-length': '70', 'vary': 'Accept-Encoding', 'server': 'Apache', 'x-backside-transport': 'FAIL FAIL', 'connection': 'close', 'date': 'Tue, 14 Apr 2015 21:15:33 GMT', 'content-type': 'application/json'})
{"error":"Service does not exist","code":"SoftLayer_Exception_Public"}

The following commands failed as well
 slcli metadata backend_ip
  slcli metadata backend_mac
  slcli metadata datacenter
  slcli metadata datacenter_id
  slcli metadata fqdn
  slcli metadata frontend_mac
  slcli metadata id
  slcli metadata ip
  slcli metadata network
  slcli metadata provision_state
  slcli metadata tags
  slcli metadata user_data

The problem is reproduced using API SoftLayer python client version 4, using version 3 of the client to run the 'sl metadata tags' command works with no problems

**Comment by sudorandom** [comment]
Thanks @MiguelHigorre. This is using the latest master, right?

**Comment by MiguelHigorre** [comment]
Yep, I used latest master, I used 'pip install git+git://github.com/softlayer/softlayer-python.git' command to install the client

**Comment by sudorandom** [comment]
I opened a PR (#526) with what I believe is a fix for this. Let me know if it works for you.

**Comment by MiguelHigorre** [comment]
Is this fix available in your github reporsitory "https://github.com/sudorandom/softlayer-api-python-client"

**Comment by sudorandom** [comment]
Yeah, I think you can use this command to install from the right branch:

```
pip install 'git+git://github.com/sudorandom/softlayer-api-python-client.git@metadata-fix'
```

**Comment by MiguelHigorre** [comment]
The fix worked, now the 'slcli metadata tags' command works

Thanks.
