### ISSUE TITLE
[Bug] slcli config setup doesnt accept default value when one is already present

### ISSUE THREAD

**Issue by ju2wheels** [softlayer/softlayer-python#529]
When you already have a `.softlayer` configured, and you `slcli config setup`, it loads previous values from `.softlayer` and shows them to you, but pressing enter at the prompt doesnt keep the previous value and move on to the next setting, it sits there and forces you to retype it and it shouldnt do that.

It also doesnt prompt for a timeout value, it should prompt and accept no value provided as meaning dont set and use default.

Using 4.0.0

**Comment by sudorandom** [comment]
Thanks, I'll get this fixed soon. I'll wait a couple days before pushing out a 4.0.1 in case there are other bugs like this.

**Comment by ju2wheels** [comment]
Not sure if the python implementation allows for user_agent like the Ruby one, didnt see that in there either.

**Comment by sudorandom** [comment]
It does at the programmatic level, not as part of the config file or the CLI: https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/API.py#L66

**Comment by sudorandom** [comment]
This should be fixed in master. A bug fix release will likely be done tomorrow.
