### ISSUE TITLE
Python CLI and SDK encounter response errors after API endpoint upgrade

### ISSUE THREAD

**Issue by rhodgin** [softlayer/softlayer-python#555]
The API endpoint upgrade (Event 18749729) that occurred yesterday introduced an issue for some installations of the SoftLayer Python SDK and CLI. In the upgrade it noted:
*Notable changes to the API endpoints include:*
*- SHA-2 SSL certificates*
*- Additional SSL ciphers and Forward Secrecy (FS/PFS) support.*

What we then encountered were some errors when connections were made to the XMLRPC endpoint. The error message was:
``` ExpatError: not well-formed (invalid token): line 1, column 0 ```
but closer examination revealed illegible response results from the service. We were able to resolve this issue by using pip to upgrade the requests module from 2.6.1 to 2.7.0. The release notes for 2.7.0 indicate some bug fixes that were needed:
*Updated urllib3 to 1.10.4, resolving several bugs involving chunked transfer encoding and response framing.*

Would you please update the setup.py file to require the 2.7.0 of requests (requests >= 2.7.0) instead of not specifying a release level?

**Comment by sudorandom** [comment]
Yes, we can update the setup.py to take 2.7 and above. Thanks for the information.
