### ISSUE TITLE
need Prompt options

### ISSUE THREAD

**Issue by c4po** [softlayer/softlayer-python#556]
in v3.3.1 we have 

```
Prompt Options:
  -y, --really  Confirm all prompt actions
```
in ```sl vs``` command

when I upgrade to v4, this option is gone.
we are automating the VS creation and deletion with scripts. We need an option to skip the prompts.

**Comment by sudorandom** [comment]
It still exists, but the option has to be specified right after the `slcli` command:

For example:
```
slcli --really vs cancel 12345
slcli -y vs cancel 12345
```

`slcli --help` shows the option:
```
  -y, --really               Confirm all prompt actions
```

**Comment by c4po** [comment]
thank you.
