### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by doubletb00** [softlayer/softlayer-python#560]
Downloaded the current SoftLayer client today (June 4, 2015 - version 4.0.2) and installed it on a Windows machine using Python version 3.4.3, and script 'import' statements are throwing the following error:

```
import SoftLayer
  File "C:\Python34\lib\site-packages\SoftLayer\__init__.py", line 18, in <module>
    from SoftLayer import consts
ImportError: cannot import name 'consts'
```

Reverted to client from March 2015 (v 3.3.1) and error does not occur.

**Comment by sudorandom** [comment]
Sorry for the extremely delayed response. I'm not sure what's going on here...  This seems to work fine for me on Windows. I'm going to leave this open in case more details come to light.

I'd check these things first:
 * what's on the python path (`python -c "import sys; print sys.path"`)
 * check to see if consts.py is actually in this directory `C:\Python34\lib\site-packages\SoftLayer\`

**Comment by sudorandom** [comment]
I'm going to close this until we can diagnose this further. Feel free to re-open if this is still an issue and you can give a bit more detail.
