### ISSUE TITLE
Unable to call API for Autoscale group.

### ISSUE THREAD

**Issue by niravhjoshi** [softlayer/softlayer-python#564]
Hi Expert,

I am trying to get SL Account Autoscale details for the specifics number of instances spin up in the autoscale group and trying to get their IP Address details.

I am trying with following code but it is not taking it. Could you please help me here is this supported method and if it is how to achieve it.

Works fine:
__author__ = 'Nirav'
import SoftLayer

client = SoftLayer.create_client_from_env(config_file="C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\softlayer")
res = client['Account'].getObject()
print(res)

Does not work:
__author__ = 'Nirav'
import SoftLayer

client = SoftLayer.create_client_from_env(config_file="C:\\Users\\IBM_ADMIN\\AppData\\Roaming\\softlayer")
res = client['SoftLayer_Scale_Group'].getObject()
print(res)

Error Message:
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\SoftLayer\transports.py", line 143, in __call__
    return utils.xmlrpc_client.loads(response.content)[0][0]
  File "C:\Python33\lib\xmlrpc\client.py", line 1003, in loads
    return u.close(), u.getmethodname()
  File "C:\Python33\lib\xmlrpc\client.py", line 657, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault SoftLayer_Exception: 'Object does not exist to execute method on. (SoftLayer_Scale_Group::getObject)'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/IBM_ADMIN/PycharmProjects/New/SL.py", line 5, in <module>
    res = client['SoftLayer_Scale_Group'].getObject()
  File "C:\Python33\lib\site-packages\SoftLayer\API.py", line 362, in call_handler
    return self(name, *args, **kwargs)
  File "C:\Python33\lib\site-packages\SoftLayer\API.py", line 330, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "C:\Python33\lib\site-packages\SoftLayer\API.py", line 226, in call
    return self.transport(request)
  File "C:\Python33\lib\site-packages\SoftLayer\transports.py", line 160, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception): Object does not exist to execute method on. (SoftLayer_Scale_Group::getObject)

Many Thanks for your review and time.
Pardon me for Beginner.

**Comment by underscorephil** [comment]
Howdy!

The error "Object does not exist to execute method on" appears when the API is not able to find the target object. In the example above it would be necessary to specify the ID of the SoftLayer_Scale_Group object you wish to interact with. Please see https://softlayer-python.readthedocs.org/en/latest/api/client.html#making-api-calls for details.
