### ISSUE TITLE
SSL error on empty Ubuntu 14.04 

### ISSUE THREAD

**Issue by redwolfsecurity** [softlayer/softlayer-python#577]
On clean, never used empty Ubuntu14.04-64 Minimal I get SSL errors. The interesting thing, it doesn't always happen and sometimes 'pip install requests[security]' resolves my problem.

Command: slcli -y --format json vs detail {system_name}

Error:
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

This is how I install the Softlayer cli:
apt-get update
apt-get upgrade
apt-get install python-pip
apt-get install python-dev libffi-dev libssl-dev libxml2-dev libxslt1-dev
pip install requests[security]
pip install --upgrade pyOpenSSL
pip install softlayer

**Comment by sudorandom** [comment]
Thanks for the information. This is related to #528.
