### ISSUE TITLE
Wrong comment in subnet help on slcli version 4.0.2

### ISSUE THREAD

**Issue by TyMac** [softlayer/softlayer-python#578]
It looks like there is a wrong comment in the help on slcli version 4.0.2 when using slcli subnet:

$ slcli subnet
Usage: slcli subnet [OPTIONS] COMMAND [ARGS]...

Network subnets.

Options:
-h, --help Show this message and exit.

Commands:
cancel Cancel a subnet.
create Add a new subnet to your account
detail Cancel a subnet.
list List subnets.
lookup Find an IP address and display its subnet and...

####################

You can see the output for detail is "detail Cancel a subnet" - I have also submitted this here:

https://forums.softlayer.com/forum/softlayer-services/portal/84266-is-this-an-error-in-slcli

**Comment by TyMac** [comment]
I think this is all is need to fix this "bug":

--- detail.py	2015-07-14 12:38:37.644021254 -0400
+++ detail_new.py	2015-07-14 13:08:50.655382476 -0400
@@ -1,4 +1,4 @@
-"""Cancel a subnet."""
+"""Get subnet details."""
 # :license: MIT, see LICENSE for more details.
 
 import SoftLayer
@@ -19,7 +19,7 @@
               help="Hide hardware listing")
 @environment.pass_env
 def cli(env, identifier, no_vs, no_hardware):
-    """Cancel a subnet."""
+    """Get subnet details."""
 
     mgr = SoftLayer.NetworkManager(env.client)
     subnet_id = helpers.resolve_id(mgr.resolve_subnet_ids, identifier,

**Comment by sudorandom** [comment]
Indeed, feel free to submit a pull request if you wish. Otherwise, I can do it. :+1: 

Thanks for the report.

**Comment by TyMac** [comment]
Ok thanks - it has been submitted!

**Comment by sudorandom** [comment]
It's merged in, thanks!
