### ISSUE TITLE
feature request - api for SAN volume storage

### ISSUE THREAD

**Issue by kbroughton** [softlayer/softlayer-python#579]
Since the iscsi is deprecated, it is urgent for automation of production services that there be either a CLI or python API for managing SANs.  I asked on the Softlayer Support ticketing system about a timeline for this feature, but was directed here.

It seems to me, iscsi should not have been deprecated until SAN was feature complete, and for me that means the feature must have a way of being automated.  Is there any timeline for adding SAN to the python api?

**Comment by underscorephil** [comment]
@kbroughton, working on it!

**Comment by allmightyspiff** [comment]
https://github.com/softlayer/softlayer-python/pull/672 should address everything here.

**Comment by sudorandom** [comment]
Completed as part of #672.
