### ISSUE TITLE
slcli server create - please add --no_public option and remove --vlan-public, --vlan-private 

### ISSUE THREAD

**Issue by ggrunin** [softlayer/softlayer-python#582]
Please add --no_public option to the SoftLayer/CLI/server/create.pl to enable provisioning with the private uplink only:
@click.option('--no_public',
              is_flag=True,
              help="Private network only")
The code to use that option is already present.
Also, please delete --vlan-public, --vlan-private  options, since we can no longer specify VLANs for the bare metal standard configurations.

**Comment by sudorandom** [comment]
This has been merged/released.
