### ISSUE TITLE
SoftLayerAPIError: The price for 0 GB Bandwidth (#78557) is not valid.

### ISSUE THREAD

**Issue by pravinlm** [softlayer/softlayer-python#583]
We are trying to create Bare Metal servers through slcli but its failing with below error.
SoftLayerAPIError(SoftLayer_Exception_Public): The price for 0 GB Bandwidth (#78557) is not valid for location ams01.

we are trying following command.
slcli server create --datacenter ams01 --size D2690_128GB_2X600GBSAS_RAID1 --os CENTOS_6_64 --vlan-private 892231 --billing=hourly --test --port-speed=100 --hostname sds1b --domain sl.com

could you please help us in resolving this error

**Comment by sudorandom** [comment]
This is likely fixed with this change which is now is master: #574. http://softlayer-python.readthedocs.org/en/latest/install.html#from-source
