### ISSUE TITLE
MetadataManager get function

### ISSUE THREAD

**Issue by galbraun** [softlayer/softlayer-python#590]
i can see that in the get function you are using the service "Resource_Metadata" and using the METADATA_MAPPING to call the relevant function.
for an example i tried to get a domain with metadata.get("domain"), and for some reason i kept getting the error :
"SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(Client): Function ("Domain") is not a valid method for this service"
and when looking in the resource page :
http://sldn.softlayer.com/reference/services/SoftLayer_Resource_Metadata
as you can see all the function as a "get" before them, and when i changed the code manually so it will call "getDomain" but then i get "Access Denied".
Is this an Issue or I'm missing something?

**Comment by sudorandom** [comment]
I'm pretty sure I know what's going on.

The metadata service is only available with the REST-like API endpoint. When standing up a MetadataManager instance, unlike every other manager, the API client is optional (https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/metadata.py#L58). If you don't pass in a SoftLayer.Client instance it will create an a client using the private REST API endpoint for you.

With that context, this should work:

```python
import SoftLayer
mgr = SoftLayer.MetadataManager()
mgr.get('domain')
```

**Comment by sudorandom** [comment]
I'm closing this issue until there's an update with this that signals that this is an ongoing issue.
