### ISSUE TITLE
Response from the API based server requests is so BAD

### ISSUE THREAD

**Issue by kgrvamsi** [softlayer/softlayer-python#616]
The request in creating the server through the api takes a alot of time infact with the mentioned time line to deleiver(20mins) its taking beyond the time it was supposed to be and if we delete a server and launch a new one it gets halted at the Assign Host Stage.

Can you suggest upon a Good Datacenter which can respond quickly for any API based requests.

**Comment by underscorephil** [comment]
Howdy @kgrvamsi!

Our support staff would have the most up to date information for you regarding this. The best way to get ahold of them is though the support ticket system or chat in the user portal(control.softlayer.com).

If you run into any issues getting ahold of them, please feel free to reach out to me(pjackson@softlayer.com)
