### ISSUE TITLE
can i pass provision script to slcli in case of bare metal server?

### ISSUE THREAD

**Issue by aibrahim** [softlayer/softlayer-python#619]
Hello, 
is it possible o pass provision scripts to bare metal servers, using slcli create server ---, as an option, 
please anybody can refer me the most suitable way to do this.
Thanks in advance

**Comment by sudorandom** [comment]
You should be able to use the `--postinstall` option when using the `slcli server create` command.

```bash
> slcli server create -h | grep postinstall
  -i, --postinstall TEXT      Post-install script to download
```
