### ISSUE TITLE
API call to show which hypervisor a VM resides on.

### ISSUE THREAD

**Issue by silentbinary** [softlayer/softlayer-python#624]
I have been looking at the API documentation and cant find what I need, so apologies for the question in advance.  Is there an API call that will show which physical hypervisor a virtual machine resides on.

Thanks in advance.

**Comment by sudorandom** [comment]
Paging @underscorephil / @allmightyspiff

**Comment by underscorephil** [comment]
@silentbinary the closest thing you can get is the location of the physical server. Take a peek at this: https://softlayer.github.io/ruby/server_locate/

**Comment by allmightyspiff** [comment]
If the virtualGuest is on a Private Cloud instance, you could use the [SoftLayer_Virtual_Guest->host](http://sldn.softlayer.com/reference/datatypes/SoftLayer_Virtual_Guest) relational property

If not, using SoftLayer_Virtual_Guest->location->pathString (like in @underscorephil's example) would be the best way.
