### ISSUE TITLE
feature request - autoscaling for python api

### ISSUE THREAD

**Issue by kbroughton** [softlayer/softlayer-python#627]
Is this in the works already?

If not is this apache-libcloud fork officially supported or recommended by softlayer?
https://github.com/Cloud-Elasticity-Services/as-libcloud

The above uses apache libcloud as a basis rather than softlayer/softlayer-python
https://github.com/Cloud-Elasticity-Services/as-libcloud/blob/trunk/libcloud/autoscale/drivers/softlayer.py

Is apache libcloud also supported by softlayer?  I"m trying to decide which would be the best basis for contributing modules for ansible automation.

**Comment by underscorephil** [comment]
Howdy @kbroughton !

I am not aware of any active movement towards getting auto scale working with the python project. If auto scale is a requirement, it may be best to go with libcloud.

**Comment by allmightyspiff** [comment]
https://github.com/softlayer/softlayer-python/tree/autoscale

### TODO: Unit Tests


|Name|   Cover|   Missing | Assigned |
| ---- |  -------| --------  |    --------|
|SoftLayer/CLI/autoscale/detail.py  | 14%  | 19-93| @ATGE  |
|SoftLayer/CLI/autoscale/logs.py |   45%  | 20-37| @caberos |
|SoftLayer/CLI/autoscale/scale.py |  35%  | 24-55| @caberos  |
|SoftLayer/CLI/autoscale/list.py  |  44% |  17-29| @FernandoOjeda  |
|SoftLayer/managers/autoscale.py  |   38% |  14, 22-25, 34-40, 49-54, 64, 73, 83| @FernandoOjeda  |


@ATGE, @caberos, @FernandoOjeda I could use some help writing these unit tests. Let me know if there are any issues you uncover. Make your pull request against the `autoscale` branch. Thanks

**Comment by drjeep** [comment]
As discussed over at IBM Cloud, having the ability to tag all members of an autoscale group would be very helpful for things like Ansible dynamic inventory

https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html

**Comment by allmightyspiff** [comment]
@drjeep Thanks for the comment. I'll be adding a command `slcli autoscale tag` to allow the tagging of all guests that are currently part of a group. 

Sadly I don't really know of a better way of automatically managing these tags when the guests are created.

**Comment by allmightyspiff** [comment]
This feature will be in v5.8.1
