### ISSUE TITLE
Transaction status 'slcli vs detail' versus 'slcli call-api Virtual_Guest getActiveTransaction'

### ISSUE THREAD

**Issue by greyhoundforty** [softlayer/softlayer-python#631]
Getting different transaction information using the following calls:

```
~ ➜  slcli --format=raw vs detail cluster1 |grep transaction
active_transaction  NULL

~ ➜  slcli --format=raw call-api Virtual_Guest getActiveTransaction --id=xxxxxxxx
(output)
transactionStatus  friendlyName     Setup provision configuration
                   name             CLOUD_PROVISION_SETUP
                   averageDuration  1.35
```

**Comment by sudorandom** [comment]
Interesting.. I can't seem to replicate this using v4.1.1, which is the latest release. Could you let me know the output of this command?

```
slcli --version
```

**Comment by greyhoundforty** [comment]
I am also on 4.1.1 but on OS X 

```
~ ➜  slcli --version                                                                                                                                                       
slcli (SoftLayer Command-line), version 4.1.1
```

**Comment by sudorandom** [comment]
@greyhoundforty alright, thanks. If you can reproduce it again, can you run the commands like this (with the -vvv option):

```
~ ➜  slcli -vvv --format=raw vs detail cluster1

~ ➜  slcli -vvv --format=raw call-api Virtual_Guest getActiveTransaction --id=xxxxxxxx
```

This will be very spammy. Can you paste the result of that? Be warned, this will include your username and API key and the default server username/password. Triple-check to make sure that you remove that information before pasting it here. If you are concerned that you might have missed something, you can email the results to my softlayer email: kmcdonald@softlayer.com

The most likely cause of this that I can think of so far is that this is a permissions issue. If you can email me your username, I might also be able to determine what's causing this.

**Comment by greyhoundforty** [comment]
Went ahead and emailed you the output as well as username.

**Comment by sudorandom** [comment]
I'm going to go ahead and close this. This is likely an odd API issue involving a unique condition that was discussed offline.
