### ISSUE TITLE
Image export/import softlayer images using slcli

### ISSUE THREAD

**Issue by akankshajain** [softlayer/softlayer-python#632]
Is there any option to export/import softlayer images using slcli?

**Comment by sudorandom** [comment]
Import, yes, but the image has to first be uploaded to object storage (which isn't currently supported in slcli). slcli image import. See http://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest_Block_Device_Template_Group/createFromExternalSource for more information about that API call. The user experience could be made much better with this feature.

Export, no. I don't think that's supported with the API at this time. Feel free to correct me if I'm wrong @underscorephil.
