### ISSUE TITLE
Ticket, attach hardware/virtual machine

### ISSUE THREAD

**Issue by underscorephil** [softlayer/softlayer-python#667]
Add support to add/list/remove ticket to device relationships

# CLI
```
slcli ticket create --title='plz halp' --subject-id=$SUBJECTID --body='me' --device=1234
```
We may have to add in switches to differentiate hardware/vs
```
slcli ticket create --title='plz halp' --subject-id=$SUBJECTID --body='me' --hardware=1234
slcli ticket create --title='plz halp' --subject-id=$SUBJECTID --body='me' --virtual=1234
```
# Referenced methods
## Virtual
http://sldn.softlayer.com/reference/services/SoftLayer_Ticket/addAttachedVirtualGuest
http://sldn.softlayer.com/reference/services/SoftLayer_Ticket/removeAttachedVirtualGuest
http://sldn.softlayer.com/reference/services/SoftLayer_Ticket/getAttachedVirtualGuests
## Hardware
http://sldn.softlayer.com/reference/services/SoftLayer_Ticket/addAttachedHardware
http://sldn.softlayer.com/reference/services/SoftLayer_Ticket/removeAttachedHardware
http://sldn.softlayer.com/reference/services/SoftLayer_Ticket/getAttachedHardware

**Comment by camporter** [comment]
This issue should be addressed in master now :shipit:
