### ISSUE TITLE
Obtain KVM console IP address and port for a virtual server via the API

### ISSUE THREAD

**Issue by smaccona** [softlayer/softlayer-python#671]
Is it possible to obtain the KVM console  IP address and port for a virtual server?

The control panel/portal allows connecting to the KVM console for a VS, but the browser plugin it uses does not work in Chrome (at least on OS X), so our current workflow is to:
- Login to the SoftLayer control panel
- Navigate to the details page for the VS in question
- Use the menu to open the KVM Console page
- Copy the IP address and port
- Open a VNC Viewer
- Manually connect to the KVM instance from the VNC Viewer

Since we are using LUKS, we have to manually enter passwords everytime we reboot a server and so we have to follow this workflow. It would be very useful for us to open the VNC Viewer from the command line like we do for everything else.

Thanks!

**Comment by smaccona** [comment]
Bump - SoftLayer folks, no ideas on this?

**Comment by sudorandom** [comment]
cc: @allmightyspiff @underscorephil

**Comment by allmightyspiff** [comment]
```bash
 slcli --format=json call-api SoftLayer_Virtual_Guest getConsoleIpAddressRecord --id=12345567 --mask="mask[ipAddress]"
```

**Comment by sudorandom** [comment]
In python:
```python
ip_addr = client.call('SoftLayer_Virtual_Guest ', 'getConsoleIpAddressRecord', id=12345567)['ipAddress']
```

I'm going to go ahead and close this issue.

**Comment by smaccona** [comment]
Excellent - thanks so much guys!
