### ISSUE TITLE
Show additional user accounts in server/vsi details

### ISSUE THREAD

**Issue by greyhoundforty** [softlayer/softlayer-python#673]
I was testing a Plesk server and when retrieving the passwords for the instance the slcli only returned the root user whereas the user to log in to the Plesk panel is admin. The admin user and password were listed in the portal however. 

```
slcli --format=raw vs detail XXXXXXX --passwords|grep users
users               root  PASSWORD
```

I would like to propose a feature request to have the cli list any user that is in the portal. This would also be handy when users add sudo users to the portal.

**Comment by sudorandom** [comment]
@greyhoundforty this should actually be the behavior. the "users" row can span multiple rows. Try this out with a server with multiple configured users in the portal to see.

**Comment by sudorandom** [comment]
Not that you can miss the extra users when grepping because "users" doesn't appear on every line that there may be user creds

**Comment by greyhoundforty** [comment]
@sudorandom Thanks. I just noticed that it is working with my Vyatta box.
