### ISSUE TITLE
ansible modules for automation

### ISSUE THREAD

**Issue by kbroughton** [softlayer/softlayer-python#686]
This isn't really a request for the softlayer-python repo, but it would be great if some people on the softlayer-python team would consider contributing a few modules to improve the softlayer offering.

To date there is only a dynamic inventory script and an instance creation script.
Ansible 2.1 roadmap was just announced. Most other cloud vendors with insufficient modules support plan major additions. Softlayer is not mentioned.

https://github.com/ansible/ansible/blob/devel/ROADMAP.md

ansible cloud modules are simple python wrappers that provide an idempotent, yaml-based dsl for cloud apis.

you may close this ticket.

**Comment by sudorandom** [comment]
cc: @underscorephil @allmightyspiff

Closing this issue as instructed.
