### ISSUE TITLE
can not run iscsi list uisng slcli

### ISSUE THREAD

**Issue by cuiliquan** [softlayer/softlayer-python#697]
It throw an error when When run slcli iscsi list, other command is ok, anyone can help fix the issue? thanks!

[scopsadm@ussj1d-scop01-ucdev ~]$ slcli iscsi list
An unexpected error has occured:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/core.py", line 173, in main
    cli.main(**kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/CLI/iscsi/list.py", line 31, in cli
    iscsi['serviceResource']['datacenter'].get('name',
KeyError: 'datacenter'

Feel free to report this error as it is likely a bug:
    https://github.com/softlayer/softlayer-python/issues

**Comment by sudorandom** [comment]
@cuiliquan It's weird that there seems to be an iscsi share that's not in a datacenter.. but I'll make the code able to handle this case. Thanks for the bug report.

**Comment by sudorandom** [comment]
@cuiliquan I've pushed a fix for this issue into master. You get get the change immediately by installing from git directly: http://softlayer-python.readthedocs.org/en/latest/install.html#from-source

**Comment by cuiliquan** [comment]
Hi Kevin

We can not provision a new cci instance using image template after we 
upgrade the slcli to latest version, could you please take a look at the 
issue, thanks!

 slcli -y vs create --image=967301 --cpu=4 --memory=8192 --san 
--vlan-private=789  --datacenter=dal06 --hostname=ussj1d-scopclark-ws 
--domain=smartercitiescloud.com --private --network=1000Mbps
SoftLayerAPIError(SoftLayer_Exception_InvalidValue): Invalid value 
provided for 'blockDeviceTemplateGroup.globalIdentifier'. A valid global 
identifier is required for a template.
[scopsadm@usda5p-scop01-ucdpxy ~]$

Clark (Li quan Cui 崔利权)
Application Specialist
Smarter Cities Cloud Ops
Industry Solution Development, China Software Development Lab, Beijing
Internet Mail: cuiliq@cn.ibm.com
地址: 北京市海淀区东北旺西路8号中关村软件园19号楼(钻石大厦) B座   邮编：
100193

**Comment by cuiliquan** [comment]
We can not provision a new cci instance using image template after we upgrade the slcli to latest version, could you please take a look at the issue, we can provision cci instance before using the same comand, thanks!

 slcli -y vs create --image=967301 --cpu=4 --memory=8192 --san --vlan-private=789  --datacenter=dal06 --hostname=ussj1d-scopclark-ws --domain=smartercitiescloud.com --private --network=1000Mbps
SoftLayerAPIError(SoftLayer_Exception_InvalidValue): Invalid value provided for 'blockDeviceTemplateGroup.globalIdentifier'. A valid global identifier is required for a template.
[scopsadm@usda5p-scop01-ucdpxy ~]$

**Comment by sudorandom** [comment]
Are you sure that command works with version 4.1.1? You can verify by explicitly installing that version with `pip install softlayer==4.1.1`.

The one thing that I do see 'wrong' with the create call is that the `--image` option is the integer ID for the object. It seems that `slcli vs create` (and SoftLayer_Virtual_Guest::createObject) has always only accepted the global identifier for the `--image` option. You can get the global identifier by running this command:

```
slcli image detail 967301
```

The thing that we did change between version is `slcli image list` to show IDs instead of global identifiers. There's 3 ways to make this better:

1. Be more explicit in the description for the `--image` option for `slcli virtual create`
2. Show global identifiers in the `slcli image list` command again
3. Have `slcli virtual create` automatically translate the image ID to the image global identifier

I created #704 to track this.

**Comment by cuiliquan** [comment]
my old slcli is different from new version 5.0.0.0, you can close the 
ticket, I have update my script, thanks for your help!


Clark (Li quan Cui 崔利权)
Application Specialist
Smarter Cities Cloud Ops
Industry Solution Development, China Software Development Lab, Beijing
Internet Mail: cuiliq@cn.ibm.com
地址: 北京市海淀区东北旺西路8号中关村软件园19号楼(钻石大厦) B座   邮编：
100193

**Comment by underscorephil** [comment]
@sudorandom I am digging option 3. This would provide the best UX with a not-super-crazy amount of overhead
