### ISSUE TITLE
IPv6 subnets always have empty hardware list.

### ISSUE THREAD

**Issue by Roguelazer** [softlayer/softlayer-python#698]
IPv6 subnets always seem to return an empty Hardware list, even when I can clearly see from the portal that a given subnet contains the primary IPs for many machines.

```python
import SoftLayer

client = SoftLayer.create_client_from_env(timeout=10)
network = SoftLayer.managers.network.NetworkManager(client)
print network.get_subnet(X, mask='hardware')['hardware']
# []
print network.subnet.getHardware(id=X)
# [] 
```

This is extra-irritating because the primary IPv6 address *also* is never returned when fetching a hardware object.

### Expected Behavior

The connected hardware in an IPv6 subnet can be discovered through the API

### Actual Behavior

The hardware list is always empty

### Environment Information
Operating System: CentOS
softlayer-python version (`slcli --version`): `slcli (SoftLayer Command-line), version 4.1.1`

**Comment by sudorandom** [comment]
It seems that this issue has been mitigated here: http://stackoverflow.com/questions/36045506/softlayer-api-and-ipv6-subnets

At the very least, this is an API issue instead of a bindings issue. Bug reports for the API itself currently are handled by customer tickets.
