### ISSUE TITLE
Getting error "The property 'hostname' must be set to create an instance of 'SoftLayer_Virtual_Guest'."

### ISSUE THREAD

**Issue by Pandiarajan90** [softlayer/softlayer-python#699]
Hi All,

I am facing issue in creating new instance with a input file.

I have a created a file called "object.txt" with following inputs
**_object.txt_**

{
 'datacenter' : {
        "name": "sng01",
    },
    'hostname': 'myserver',
    'domain': 'domain.com',
    'startCpus': 1,
    'maxMemory': 1024,
    'hourlyBillingFlag': 'true',
    'operatingSystemReferenceCode': 'UBUNTU_LATEST',
    'localDiskFlag': 'false'
}

And this is my create_new_instance.py script file.
**_create_new_instance.py_**

#!/usr/bin/env python

import SoftLayer
username = 'your user id'
key = 'your API key'

try:
client = SoftLayer.Client(username=username, api_key=key)

obj = open('object.txt',"r")
f=obj.read()
print f        

creat_new_instance = client['Virtual_Guest'].createObject(f)

_**Output:**_

{
 'datacenter' : {
        "name": "sng01",
    },
    'hostname': 'trail6',
    'domain': 'sumtwo.com',
    'startCpus': 1,
    'maxMemory': 1024,
    'hourlyBillingFlag': 'true',
    'operatingSystemReferenceCode': 'UBUNTU_LATEST',
    'localDiskFlag': 'false'
}

Traceback (most recent call last):
  File "./create_new_instance.py", line 62, in <module>
    creat_new_instance = client['Virtual_Guest'].createObject(obj)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/API.py", line 373, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/API.py", line 341, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/API.py", line 237, in call
    return self.transport(request)
  File "/usr/local/lib/python2.7/dist-packages/SoftLayer/transports.py", line 187, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_MissingCreationProperty): The property 'hostname' must be set to create an instance of 'SoftLayer_Virtual_Guest'.

If i give object input directly in command means it works charm..but in input calling file it shows error.
Kindly help me to short this out.

Thanks 
Pandiarajan

**Comment by sudorandom** [comment]
This is more of a python comprehension issue than a softlayer-python problem but I'll try to help:

When you're reading in object.txt with open() you're not transforming it into a complex python object that you seem to think you are. Your variable, `f` is just a string. It's not a dictionary. You can see this yourself by printing type(f). You'd either need to evaluate your `object.txt` as python code (which I don't recommend) or convert to a more appropriate format like JSON. You're getting an error saying that there's no hostname because hostname happens the first thing that's checked.

Here's how to do this with JSON:

object.json
```
{
    "datacenter": {"name": "sng01"}
    "domain": "domain.com",
    "hourlyBillingFlag": true,
    "localDiskFlag": false,
    "maxMemory": 1024,
    "hostname": "myserver",
    "startCpus": 1,
    "operatingSystemReferenceCode": "UBUNTU_LATEST"
}
```

example_create.py
```
#!/usr/bin/env python
from __future__ import print_function
import SoftLayer
import json

username = 'your user id'
key = 'your API key'

client = SoftLayer.Client(username=username, api_key=key)

with open('object.txt',"r") as json_file:
    instance_details = json.loads(obj.read())

    new_instance = client.call('Virtual_Guest',
                               'createObject',
                               instance_details)
    print(new_instance)
```

**Comment by Pandiarajan90** [comment]
Thanks @sudorandom for the help..Using json input it works fine..
