### ISSUE TITLE
Can we get IQN id, username and password, authorize host using SL API for endurance storage?

### ISSUE THREAD

**Issue by cuiliquan** [softlayer/softlayer-python#729]
The password is empty, can we get IQN id, username and password, authorize host using SL API? 
slcli iscsi detail 10816683
:.................................:......................................:
:                            name : value                                :
:.................................:......................................:
:                              id : 10816683                             :
:             serviceResourceName : PerfStor Aggr aggr_staassjc0101_hp01 :
:                      createDate : 2016-04-27T13:39:48+08:00            :
:                         nasType : ISCSI                                :
:                      capacityGb : 100                                  :
:                   mountableFlag : 1                                    :
: serviceResourceBackendIpAddress : 10.1.206.90                          :
:                           price : {}                                   :
:                   BillingItemId : {}                                   :
:.................................:......................................:
[scopsadm@ussj1d-scop01-ucdpxy ~]$

**Comment by sudorandom** [comment]
There is a new set of commands under `slcli block` that might have what you want.

**Comment by cuiliquan** [comment]
thanks for your help, can the slcli can be authorize hosts for this endurance storage?

**Comment by sudorandom** [comment]
@cuiliquan not yet. Feel free to open a separate issue so we can track that as a feature request.
