### ISSUE TITLE
Feature Request: Add functionality to authorize hosts with slcli block

### ISSUE THREAD

**Issue by lukecoll** [softlayer/softlayer-python#731]
### Expected Behavior
An extension of the item https://github.com/softlayer/softlayer-python/issues/729
We would like there to be a command which allows us to authorize hosts to storage using the CLI.

### Actual Behavior
Unable to authorize hosts with the slcli block command(s). Task must be completed via Web UI.

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.1.0

Please let me know if we opened this incorrectly.

**Comment by lukecoll** [comment]
Also if this is available via other API implementations please let me know so we can implement a stop-gap on our side.

**Comment by vmtyler** [comment]
The code exists here: https://github.com/iodine53/softlayer-python/tree/block-storage-host-auth
I'm working on test coverage and will submit it as a PR

**Comment by sudorandom** [comment]
Closed with #742
