### ISSUE TITLE
Hardware Cancel

### ISSUE THREAD

**Issue by si5074** [softlayer/softlayer-python#737]
How do I cancel hardware? I dont see an option for a server identifier.

```
  / slcli hardware cancel -h           
Usage: slcli hardware cancel [OPTIONS] IDENTIFIER

  Cancel a dedicated server.

Options:
  --immediate     Cancels the server immediately (instead of on the billing
                  anniversary)
  --comment TEXT  An optional comment to add to the cancellation ticket
  --reason TEXT   An optional cancellation reason. See cancel-reasons for
                  a
                  list of available options
  -h, --help      Show this message and exit.
```
### Environment Information
Operating System: MAC OS X
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.1.0

**Comment by camporter** [comment]
The server identifier is just the primary argument. For example, `slcli hardware cancel 123`, `slcli hardware cancel 1.2.3.4`, or `slcli hardware cancel some.example.com` should all work.
