### ISSUE TITLE
Softlayer Hardware Size

### ISSUE THREAD

**Issue by si5074** [softlayer/softlayer-python#738]
I dont see the size option in the soft layer hardware API. This option is present in slcli hardware create-options. How does the size property relate to the SoftLayer_Hardware object ?

**Comment by camporter** [comment]
The hardware sizes correspond to presets for the Fast Server offering. The size is just a representation for what sort of hardware is being requested, such as the processor, ram, and disk configurations. It does not have a direct relationship to a specific property on SoftLayer_Hardware.
