### ISSUE TITLE
Fetching the list of datacenters from HardwareManager is missing locations?

### ISSUE THREAD

**Issue by dnwe** [softlayer/softlayer-python#743]
### Expected Behaviour

The following Python _should_ return the full set of datacenter locations that a host can be provisioned in:
```py
#!/usr/bin/python
"""
Fetch the list of datacenters from the SoftLayer API
"""

from __future__ import print_function
import SoftLayer
from SoftLayer.managers import hardware

CLIENT = SoftLayer.create_client_from_env()
HARDWARE_MANAGER = hardware.HardwareManager(CLIENT)
OPTIONS = HARDWARE_MANAGER.get_create_options()
DATACENTERS = [x['key'] for x in OPTIONS['locations']]
for center in sorted(DATACENTERS):
    print('{}'.format(center))

```

### Actual Behaviour

A number of locations are missing from the returned list. Notably dal02, dal05, hous02 and sea01. 

I was expecting to see the full set of orderable datacenters as per the output of:
```sh
elinks -dump http://www.softlayer.com/data-centers \
    | awk -F'.' '/speedtest.*softlayer.com$/{print $2}'
```

### Environment Information
Operating System:
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.1.0

**Comment by camporter** [comment]
The create options for hardware are derived from the locations available for the fast server provision package. Fast servers are not available in every datacenter, hence why you are not seeing dal02, dal05, hou02, or sea01. Other hardware/bare metal offerings are available in a variety of datacenters.

**Comment by sudorandom** [comment]
I'm hoping this answered your concerns. I'm closing this issue. Feel free to re-open if there's a follow up question to this that we can help with.
