### ISSUE TITLE
Deprecate `client['service'].call()` Usage

### ISSUE THREAD

**Issue by sudorandom** [softlayer/softlayer-python#775]
### Desired Behavior

``` python
>>> client = SoftLayer.create_client_from_env()
>>> account = client['SoftLayer_Account'].getObject()
DEPRECATION WARNING: Using the form client['SoftLayer_Account'].getObject(*args, **kwargs) is deprecated. Use client.call('SoftLayer_Account', 'getObject', *args, **kwargs) instead.
```

**Comment by sudorandom** [comment]
There are at least 104 instances where managers use client['service']. All of these instances will probably need to be updated.

**Comment by allmightyspiff** [comment]
I'm personally a big fan of client['SoftLayer_Account'].getObject() style calls.
I'm going to close this issue unless there are objections.
