### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes' by Python 3.5 "json.loads"

### ISSUE THREAD

**Issue by takemaru-hirai** [softlayer/softlayer-python#778]
I got TypeError, maybe caused by Python 3.x unicode and bytes features.
How can I avoid this?
Here is the "Getting Started" result using .softlayer file as credential.

### Expected Behavior

>>> import SoftLayer
>>> client = SoftLayer.create_client_from_env()
>>> resp = client.call('Account', 'getObject')
>>> resp['companyName']
'Your Company'

### Actual Behavior

$ python
Python 3.5.2 (default, Oct 25 2016, 14:18:38)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import SoftLayer
>>> client = SoftLayer.create_client_from_env()
>>> resp = client.call('Account', 'getObject')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/softlayer/lib/python3.5/site-packages/SoftLayer/API.py", line 256, in call
    return self.transport(request)
  File "/opt/softlayer/lib/python3.5/site-packages/SoftLayer/transports.py", line 290, in __call__
    result = json.loads(resp.content)
  File "/usr/local/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

### Environment Information
Operating System: CentOS 6.6
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.2.0

**Comment by sudorandom** [comment]
The next release should actually fix this issue already. You can get a sneak peak of it by installing directly from git using the instructions here: https://softlayer-python.readthedocs.io/en/latest/install.html#from-source

It appears to have been fixed as part of #772.
