### ISSUE TITLE
It is not possible to setup the client using the the IBMid credentials

### ISSUE THREAD

**Issue by raulcabero** [softlayer/softlayer-python#783]
Currently when you try to setup the client configuration using the IBMid credentials (the one used to log on to control portal), the client throws the following error message:

SoftLayerAPIError(SoftLayer_Exception_User_Customer_LoginFailed): Invalid login credentials provided.

please see:
http://stackoverflow.com/questions/40797208/softlayer-invalid-login-credentials-provided

It seems that the issue is due to the Python client uses the: 
http://sldn.softlayer.com/reference/services/SoftLayer_User_Customer/getPortalLoginToken method to get the APIKey, however, this method does not work for IBMid, it uses this method:

http://sldn.softlayer.com/reference/services/SoftLayer_User_Customer_OpenIdConnect/getPortalLoginTokenOpenIdConnect

**Comment by allmightyspiff** [comment]
Going to fix this in #1104
