### ISSUE TITLE
What softlaryer API version are currently supported

### ISSUE THREAD

**Issue by mingkui** [softlayer/softlayer-python#784]
One of our client is asking the supprot roadmap about 3.0.2 and 5.2.1. Can you provide on it? 

**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):

**Comment by camporter** [comment]
I'm sure I understand what the question here is.

**Comment by allmightyspiff** [comment]
The Python Client is at version 5.2.1
The SoftLayer API that the Python Client supports is V3
