### ISSUE TITLE
sl config setup error

### ISSUE THREAD

**Issue by mingkui** [softlayer/softlayer-python#785]
below is the error message sent from client. Can someone help? 

# sl config setup

Username []: citi1140537_mbalu

API Key or Password []:

Endpoint (public|private|custom): custom

Endpoint URL [https://api.softlayer.com/xmlrpc/v3]:

TransportError(0): HTTPSConnectionPool(host='api.softlayer.com', port=443): Max retries exceeded with url: /xmlrpc/v3/SoftLayer_Account (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2cf46d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))

 

**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):

**Comment by camporter** [comment]
That looks like a DNS issue, not related to the client itself. Have you tried testing that you can resolve api.softlayer.com with the DNS server you are using?

**Comment by mingkui** [comment]
The client admin said he used SL 5.x worked, but 3.02 did work though.
