### ISSUE TITLE
500 Error when trying to get VirtualGuest tags.

### ISSUE THREAD

**Issue by Freyert** [softlayer/softlayer-python#786]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
[gist](https://gist.github.com/Freyert/64a81d0fe63d3adf90c5684e47fbc588)
I expect to get a list of VMs with their tags.
Mask: hostname,domain,fullyQualifiedDomainName,primaryBackendIpAddress,tagReferences
### Actual Behavior

When I include tagReferences in the mask I get:

```
Traceback (most recent call last):
  File "inventory.py", line 17, in <module>
    cluster = client.call('Account', 'getVirtualGuests', mask=mask)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/API.py", line 263, in call
    return self.transport(request)
  File "/usr/local/lib/python2.7/site-packages/SoftLayer/transports.py", line 197, in __call__
    raise exceptions.TransportError(ex.response.status_code, str(ex))
SoftLayer.exceptions.TransportError: TransportError(500): 500 Server Error: Internal Server Error for url: https://api.softlayer.com/xmlrpc/v3.1/SoftLayer_Account
```

**Comment by camporter** [comment]
Depending on the number of guests on your account, it's possible that the request is too large, so the request either needs to use result limit and offset, filtering, or information can be removed via the mask. Here's a mask which will cut out a lot of extraneous objects that get added: 
```python
mask = [
        'hostname',
        'domain',
        'fullyQualifiedDomainName',
        'primaryBackendIpAddress',
        'tagReferences[id,tag[id,name]]'
        ]
mask = ','.join(mask)
```

**Comment by allmightyspiff** [comment]
to add to what camporter said, adding in a resultLimit would also help for reducing the time a request to the API takes
500 errors like this usually mean the request to get all the needed data took too long.
