### ISSUE TITLE
SL 3.0.2 pyhtone client CCI manager post script didn't get executed

### ISSUE THREAD

**Issue by mingkui** [softlayer/softlayer-python#787]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**
SL 3.0.2 pyhtone client. 
### Expected Behavior
CCI manager post script should be executed after install
### Actual Behavior
cci manager create_instance method issue.
the post was downloaded to /root/post_install.lxRY , but it never get executed. There was not error with the scripts itself.  Why post script downloaded for create_instaance uri doesn't excuted after imaged installed?

### Environment Information
Operating System:RHEL 7
softlayer-python version (`slcli --version`): 3.0.2

**Comment by camporter** [comment]
Does the URL to your script use HTTPS?

**Comment by mingkui** [comment]
No. I used something like http://xxxxxx.com/script/myscript.sh link. Should we use htttps?

**Comment by mingkui** [comment]
changed to https worked. Thanks!
