### ISSUE TITLE
Can't order hardware in Oslo datacenter (osl01)

### ISSUE THREAD

**Issue by msambol** [softlayer/softlayer-python#790]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

This code is raising an error when trying to order hardware in `osl01`:
https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/hardware.py#L735-L742

More information: http://stackoverflow.com/questions/41293398/softlayer-api-doesnt-recognize-new-datacenter-osl01

### Expected Behavior
A successful baremetal order.

### Actual Behavior
```
  File "/home/blueboxadmin/sambol/venv/local/lib/python2.7/site-packages/SoftLayer/managers/hardware.py", line 738, in _get_location
    % location)
SoftLayer.exceptions.SoftLayerError: Could not find valid location for: 'osl01'
```

### Environment Information
Operating System: Ubuntu 14.04
softlayer-python version (`slcli --version`): 5.2.1

**Comment by msambol** [comment]
@sudorandom

**Comment by allmightyspiff** [comment]
I believe this should be fixed now.

```bash
$ slcli hw create
Hostname: cgallo
Domain: test.com
Size: S1270_32GB_1X1TBSATA_NORAID
Os: COREOS_CURRENT_64
Datacenter: osl01
Port speed: 1000
This action will incur charges on your account. Continue? [y/N]: y
:.........:...........................:
:    name : value                     :
:.........:...........................:
:      id : 16911101                  :
: created : 2017-07-19T09:23:41-06:00 :
:.........:...........................:
```
