### ISSUE TITLE
use sl or slcli?

### ISSUE THREAD

**Issue by tseelbach** [softlayer/softlayer-python#791]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
sl should work - or not?

This page shows a mix of sl and slcli usage:   
https://softlayer-api-python-client.readthedocs.io/en/latest/cli/

Probably doc just needs updating?

### Actual Behavior
which sl
/Library/Frameworks/Python.framework/Versions/3.6/bin/sl
tsee at Toms-MacBook-Pro in ~
$ sl
ERROR: Use the 'slcli' command instead.

### Environment Information
Operating System:   OX X El Capitan

softlayer-python version (`slcli --version`):
 slcli --version
slcli (SoftLayer Command-line), version 5.2.1

**Comment by camporter** [comment]
`slcli` is the correct command. `sl` could be confused with the steam locomotive command  :smile:
