### ISSUE TITLE
slcli object-storage accounts empty

### ISSUE THREAD

**Issue by s4mur4i** [softlayer/softlayer-python#794]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
`slcli object-storage accounts`
list all object storage accounts on account

### Actual Behavior
`slcli object-storage accounts
:....:......:
: id : name :
:....:......:
:....:......:`
No account is found, checking on protal I have at least one s3 account

### Environment Information
Operating System: mac osx 10.12
softlayer-python version (`slcli --version`):  5.1.0

**Comment by camporter** [comment]
Can you confirm the user performing the request has permission to access the object storage information?

**Comment by s4mur4i** [comment]
Yes I can. with the account I created a new object storage for test
purpose and it is not visible.


--

  Krisztian Banhidy

  krisztian@szamuraj.com







On Thu, Jan 5, 2017, at 18:08, cmp wrote:

> Can you confirm the user performing the request has permission to
> access the object storage information?
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/softlayer/softlayer-python/issues/794#issuecomment-270698918

**Comment by allmightyspiff** [comment]
Can you try updating your slcli client to 5.2.1.
