### ISSUE TITLE
It's not possible to order File/Block Performance through SLCLI

### ISSUE THREAD

**Issue by rubercuellar** [softlayer/softlayer-python#795]
I tried the following commands:

**FILE PERFORMANCE:**

`slcli file volume-order --storage-type=performance --size=20 --iops=200 --location=dal09`

The following exception is raised:

> Usage: slcli-script.py file volume-order [OPTIONS]
> 
> Error: Missing option "--os-type".  Choose from HYPER_V, LINUX, VMWARE, WINDOWS_
> 2008, WINDOWS_GPT, WINDOWS, XEN.

**BLOCK PERFORMANCE**
`slcli block volume-order --storage-type=performance --size=20 --iops=200 --location=dal09 --os-type=LINUX`

The following exception is raised:

> Argument Error: Could not find disk space price for the given volume

 I tried with the same values through UI and It works fine.

### Expected Behavior
A File/Block Performance storage should be ordered
### Actual Behavior
An exception is raised
### Environment Information
Operating System: Windows 7
softlayer-python version (`slcli --version`):
5.2.1

**Comment by camporter** [comment]
For the first issue, an OS type is required for file storage ordering.

For the second issue, the wrong size is used to look up storage space (IOPS size instead of storage space size). I'm working on a fix.

**Comment by rubercuellar** [comment]
File Performance not require a OS Type through UI

**Comment by camporter** [comment]
Ah right. The os format doesn't apply to file storage. I'll add a change to remove that for file storage ordering.

**Comment by allmightyspiff** [comment]
both types of ordering should work properly now.

```
slcli file volume-order --storage-type=performance --size=20 --iops=200 --location=dal09
Order #12850937 placed successfully!
 > File Storage (Performance)
 > 20 GB Storage Space
 > 200 IOPS

slcli block volume-order --storage-type=performance --size=20 --iops=200 --location=dal09 --os-type=LINUX
Order #12850549 placed successfully!
 > Block Storage (Performance)
 > 20 GB Storage Space
 > 200 IOPS
```
