### ISSUE TITLE
API KeyError: orderContainers

### ISSUE THREAD

**Issue by cgongnb** [softlayer/softlayer-python#800]
We've been using our SoftLayer API script to order baremetal servers for the past year without any issues. When I tried to place a new order today using quote, 2032985, I got the following error:

  File "./order-softlayer-servers.py", line 69, in place_SoftLayerOrder
    order['orderContainers'][0]['hardware'] = []
KeyError: 'orderContainers'

The last successful order that I placed was on Jan 18, 2017. Was there a recent change to the API data model; such as orderContainers? Below is the main portion of my script.

Thank you.

import SoftLayer.API

def place_SoftLayerOrder(orderList,quote_id):
    order = getOrderContainer(quote_id)

    order['orderContainers'][0]['hardware'] = []

    for server in orderList:
        print server
        order['orderContainers'][0]['hardware'].insert(0,{'hostname': server, 'domain': 'sl-netbase.com'})

    order['orderContainers'][0]['quantity'] = len(orderList)

    order['presetId'] = None

    result = client['Billing_Order_Quote'].placeOrder(order, id=quote_id)
    pp(result)
    return result

**Comment by cgongnb** [comment]
Attached is the output from:

order = getOrderContainer(quote_id)

**Comment by camporter** [comment]
I believe I'm aware of the change that might have broken this.

**Comment by cgongnb** [comment]
Here is the getOrderContainer function:

def getOrderContainer(quote_id):
    container = client['Billing_Order_Quote'].getRecalculatedOrderContainer( id=quote_id)
    return container

**Comment by camporter** [comment]
So to workaround this, you can check if the 'orderContainers' property has a first element. If not, the base container, represented by 'order', should be modified instead.

**Comment by allmightyspiff** [comment]
https://softlayer.github.io/release_notes/20170125/

 SoftLayer_Billing_Order_Quote::getRecalculatedOrderContainer() was refactored recently, breaking this behavior.

**Comment by cgongnb** [comment]
@camporter 

We always use a quote to place orders for baremetal servers. The quote always contains one server configuration only. The order quantity is usually between 1 - 20. My scripts takes the quantity and the list of server hostnames, and inserts into the orderContainers object before the placeOrder call.

You mentioned to check if orderContainers property has a first element. I get that. There is no orderContainers from the getRecalculatedOrderContainer results, therefore, I should check the base container. However, I don't see any information for the hostname and order quantity. Nothing order related information from the pp(order) output either. Did I overlook the info in the order output?


Here is the main portion of my order script:

`    order = client['Billing_Order_Quote'].getRecalculatedOrderContainer( id=quote_id )
    pp(order)

    order['orderContainers'][0]['hardware'] = []
    for server in orderList:
        print server
        order['orderContainers'][0]['hardware'].insert(0,{'hostname': server, 'domain': 'sl.com'})

    order['orderContainers'][0]['quantity'] = len(orderList)

    order['presetId'] = None
    result = client['Billing_Order_Quote'].placeOrder(order, id=quote_id)`

Thank you for your help.

**Comment by allmightyspiff** [comment]
getRecalculatedOrderContainer now only returns a single object, instead of an array of 1 object. 

If you change your code to the following, I believe it will work properly, although I haven't tested it.
```
order['orderContainers']['hardware'] = []
for server in orderList:
    print server
    order['orderContainers']['hardware'].insert(0,{'hostname': server, 'domain': 'sl.com'})

order['orderContainers']['quantity'] = len(orderList)

order['presetId'] = None
result = client['Billing_Order_Quote'].placeOrder(order, id=quote_id)`
```

**Comment by cgongnb** [comment]
That won't work because the orderContainers no longer exists after the update on 20170125 that you mentioned earlier.

**Comment by cgongnb** [comment]
[getRecalculatedOrderContainer.txt](https://github.com/softlayer/softlayer-python/files/759255/getRecalculatedOrderContainer.txt)

Attached is the output from  client['Billing_Order_Quote'].getRecalculatedOrderContainer( id=quote_id)

I don't see any entries for orderContainers.

**Comment by allmightyspiff** [comment]
I updated my original comment. What getRecalculatedOrderContainer returns IS the order container.

What it used to return was an object with an array of 1 order container.
