### ISSUE TITLE
Support a retry functionality for intermittent failures "Connection broken: error(104, 'Connection reset by peer')"

### ISSUE THREAD

**Issue by sikhlaqu** [softlayer/softlayer-python#803]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior

**Issue:**
Our Team often place "NFS fileshare creation" request using the "softlayer-python" library.
and 20-30% of the Time the Softlayer call fails with the Below Error message
 "Connection broken: error(104, 'Connection reset by peer')"
"Connection broken: error(104, 'Connection reset by peer')"

When we Try again, it starts working. This "intermittent" failures are impacting our customers.
On few occasions, these "intermittent" failures occur more than 50% of the time.

**Expectation:**
We are expecting these "errors" should be handled by the "softlayer-python" client internally.
and the "retry" should happen.

### Actual Behavior
"Connection broken: error(104, 'Connection reset by peer')"

### Environment Information
Operating System:  Ubuntu 16.04
softlayer-python version (`slcli --version`):   SoftLayer (3.3.1)
Data Centers used : Dal09, Lon02, Ams03

**Comment by losdevnull** [comment]
We have the same problem

**Comment by vitaliyf** [comment]
These errors started happening in the past few weeks for all types of requests and they frequently come along with inability to login to control.softlayer.com. Clearly something got broken on the API side as I've never seen these issues in the past in all my years of using SL API and softlayer-python.

**Comment by camporter** [comment]
There are some issues with having the client retry requests by default. For one, there are a number of requests that --if performed more than once -- can cause unwanted behavior. One example of this would be ordering (the request could reset after the server received the request but before the response had been set).

Providing a flag to have the client retry if the user of the library wants to and perhaps a select number of CLI commands may be possible however.

**Comment by allmightyspiff** [comment]
This was addressed in v5.4.0. 

1. Upgraded requests library to support retrying on connection issues
2. add a retry() decorator for select functions that will retry on SoftLayer_API exceptions. Things like Rate limit exceeded, or internal errors.
