### ISSUE TITLE
when try create quote got error xmlrpc.client.Fault: <Fault SoftLayer_Exception: 'Object does not exist to execute method on. (SoftLayer_Billing_Order_Quote::saveQuote)'

### ISSUE THREAD

**Issue by RobertRajcool** [softlayer/softlayer-python#807]
http://sldn.softlayer.com/reference/services/SoftLayer_Billing_Order_Quote/saveQuote:

redington_client=SoftLayer.Client(api_key='DONT PUT YOUR API KEY HERE',username='xyxakfjsdfsdffd')
 redington_client.call('Billing_Order_Quote','saveQuote',{'accountId': 1262031,
 'id': 2081709,
 'name': 'TestQuote2Test',
 'quoteKey': '27f4319d9f0ae83c680253b4674dd344',
 'status': 'PENDING'})
got api error:xmlrpc.client.Fault: <Fault SoftLayer_Exception: 'Object does not exist to execute method on. (SoftLayer_Billing_Order_Quote::saveQuote)'

**Comment by allmightyspiff** [comment]
call('Billing_Order_Quote','saveQuote',QuoteObject, id= 2081709)
^^ that is what you need to do I think.

**Comment by RobertRajcool** [comment]
@allmightyspiff no i need create new order quote using account id (accountId': 1262031)

**Comment by allmightyspiff** [comment]
It looks like you already have the quote key, you can use that to get the quoteId (which I assumed was 2081709).

You can then use saveQuote to save the quote to your account for future use.

You cannot create a new quote from the API, that can only be done by someone in the sales team at SoftLayer.

**Comment by RobertRajcool** [comment]
Then how place order quote????

**Comment by RobertRajcool** [comment]
i

**Comment by camporter** [comment]
Just to clarify, you can save a quote via the API, using `SoftLayer_Product_Order` `placeOrder` with `saveAsQuote` set to `True`. You need to pass in order data as well.
