### ISSUE TITLE
Improper error message while calling slcli lb service-edit with incorrect parameters

### ISSUE THREAD

**Issue by chandan1001** [softlayer/softlayer-python#823]
**call `slcli lb service-edit  local:123456 --enabled`**

### Environment Information
Operating System: Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
slcli (SoftLayer Command-line), version 5.2.5

**Comment by allmightyspiff** [comment]
Sorry for taking so long to get around to making this update.

SoftLayer Local LoadBalancers were End Of Serviced In May  ( https://www.ibm.com/cloud/cloud-prod-life ).
This command was removed in [v5.8.0](https://github.com/softlayer/softlayer-python/releases/tag/v5.8.0)
