### ISSUE TITLE
SL portal User permissions not able to retrieve with slcli

### ISSUE THREAD

**Issue by viswan098** [softlayer/softlayer-python#827]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
what is the slcli command to display all the user IDs created in SL portal for a specific customer with their privileges in second column . Requirement is to perform a periodic user ID validation
### Environment Information
Operating System: RHEL 6.5
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.2.6

**Comment by allmightyspiff** [comment]
Added in v5.6.0: https://softlayer-python.readthedocs.io/en/latest/cli/users/, just forgot to close this issue.
