### ISSUE TITLE
Add CLI support to select 10 Gbps port speed for bare-metal servers

### ISSUE THREAD

**Issue by AugieMena3** [softlayer/softlayer-python#828]
### Expected Behavior

For fast-provision bare metal servers (the only type supported by the CLI), only unbonded interfaces support 10 Gbps.  However, both create-options and create commands exclude unbonded uplinks when consulting the catalog for port speed options.  Therefore, it is not currently possible to provision a bare-metal server via the CLI with a 10 Gbps port speed.  While this can be worked around by using the Python API, ideally this should be an option supported by the CLI.

A modified version of the CLI could yield something like the following when running 'slcli hardware create-options':

:...........................................:.......:
:                 port_speed                : value :
:...........................................:.......:
:  10 Mbps Public & Private Network Uplinks :   10  :
: 100 Mbps Public & Private Network Uplinks :  100  :
:  1 Gbps Public & Private Network Uplinks  :  1000 :
: 10 Gbps Dual Public & Private Network Uplinks (Unbonded) : 10000 :
:...........................................:.......:

This would then allow '--port-speed=10000' to be selected via the 'slcli hardware create' command.

### Actual Behavior

Current excerpt from 'sclcli hardware create-options':

:...........................................:.......:
:                 port_speed                : value :
:...........................................:.......:
:  10 Mbps Public & Private Network Uplinks :   10  :
: 100 Mbps Public & Private Network Uplinks :  100  :
:  1 Gbps Public & Private Network Uplinks  :  1000 :
:...........................................:.......:

### Environment Information
Operating System:
macOS 10.12.4

softlayer-python version (`slcli --version`):
$ slcli --version
slcli (SoftLayer Command-line), version 5.2.4

**Comment by allmightyspiff** [comment]
So, 3 years later finally getting around to this one.

First, 10G is now an option in any case... so there is that. But I think I'll do so re-working on this code to allow for unbonded/redundant links as there isn't much reason to disallow them as far as I can tell.

**Comment by allmightyspiff** [comment]
TODO: Add a flag to OSes to see if they support hourly billing or not.
