### ISSUE TITLE
Upgrade storage ordering

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#832]
currently ordering storage in SLCLI orders "Endurance / Performance Storage", should be upgraded to order "Storage as a Service" where possible.

1. Might need to consider backward compatability for DCs or Customers who want the v1 offering
2. Add a differentiator in the SLCLI for volumes in v1 and v2 offerings.

**Comment by allmightyspiff** [comment]
issues created from a conversation with @dpickle2

**Comment by bdumler** [comment]
Working on a project for hourly order for STaaS to IMS/SL including an SLCLI.    Will be interested to receive updates when the addition of STaaS ordering is completed for the SLCLI.  To add hourly ordering into the SLCLI would be similar to how the SLCLI is used to order hourly servers.  I am happy to share more detail requirements.  Bill Dumler (bdumler@us.ibm.com)

**Comment by dpickle2** [comment]
Pull request 838 has been merged in. If additional details are needed or questions arise, feel free to reach out to me.
