### ISSUE TITLE
Feature: Add slicli ssh login

### ISSUE THREAD

**Issue by houstar** [softlayer/softlayer-python#837]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
We need one cli can be directly login into baremetal or virtual machines
### Actual Behavior
Currently we can't login into baremetal via slcli ssh login bm01 like that

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):

**Comment by allmightyspiff** [comment]
I'm not sure I want to deal with launching SSH from the slcli. 
I'll leave this issue open for now incase there is a lot of support for this sort of thing though.

**Comment by houstar** [comment]
As you might know, "vagrant ssh" can be ssh-ed into vm without password. 
So I think slcli ssh login bm01  ( bm01 is baremetal hostname) is more convenience for use.
Otherwise, I must to go to Softlayer web portal to get the server details and ssh login.

**Comment by houstar** [comment]
See below examples in bold size
$ vagrant
Usage: vagrant [options] <command> [<args>]

    -v, --version                    Print the version and exit.
    -h, --help                       Print this help.

Common commands:
     box             manages boxes: installation, removal, etc.
     connect         connect to a remotely shared Vagrant environment
     destroy         stops and deletes all traces of the vagrant machine
     global-status   outputs status Vagrant environments for this user
     halt            stops the vagrant machine
     help            shows the help for a subcommand
     init            initializes a new Vagrant environment by creating a Vagrantfile
     login           log in to HashiCorp's Atlas
     package         packages a running vagrant environment into a box
     plugin          manages plugins: install, uninstall, update, etc.
     port            displays information about guest port mappings
     powershell      connects to machine via powershell remoting
     provision       provisions the vagrant machine
     push            deploys code in this environment to a configured destination
     rdp             connects to machine via RDP
     reload          restarts vagrant machine, loads new Vagrantfile configuration
     resume          resume a suspended vagrant machine
     share           share your Vagrant environment with anyone in the world
     snapshot        manages snapshots: saving, restoring, etc.
     **ssh             connects to machine via SSH**
     ssh-config      outputs OpenSSH valid configuration to connect to the machine
     status          outputs status of the vagrant machine
     suspend         suspends the machine
     up              starts and provisions the vagrant environment
     vbguest
     version         prints current and latest Vagrant version

For help on any individual command run `vagrant COMMAND -h`

Additional subcommands are available, but are either more advanced
or not commonly used. To see all subcommands, run the command
`vagrant list-commands`.

**Comment by sergiocarlosmorales** [comment]
You don't need Vagrant to connect to a server without a password.
Configure the server to use ssh key-based authentication and you can do it too (AFAIK that's how Vagrant does it).

**Comment by houstar** [comment]
I have managed lots of server in our Softlayer Cloud Environment. The real requirements is that I should paste the ip in our /etc/hosts. then ssh-copy the public key into this baremetal. 
Why not just slcli ssh login bm02 like that ? I do not need to remember the baremetal's ip and password. Just one apiKey can ssh any server I have.

**Comment by sergiocarlosmorales** [comment]
To avoid manually having to copy SSH keys you can have SoftLayer automatically do it when a server is provisioned by leveraging the [SSH Keys functionality of the API](https://knowledgelayer.softlayer.com/procedure/ssh-keys-0).

I have security concerns about having the SLCLI be able to directly log in to resources, in addition to the complications of accounting for conditions unique to each server as you can have SSH configured in many ways (if accesible at all) like network interface, port, users etc.

Let's keep this open for discussion, in the interim you can leverage SSH keys API along with some scripting on your end to achieve what you need.

**Comment by allmightyspiff** [comment]
My thoughts for this feature would be something akin to

* slcli ssh --id=12345 --public|--private --username --password
SLCLI would then pull down the public/private ip from the api, and then launch "ssh username@ip"
If --password was set, it would print out the password before launching SSH. I think filling in the password automatically is too much trouble.
MAYBE we could include searching by FQDN, but since hostname/domain don't need to be real or unique, this might be problematic if a user has 2 hosts with the same FQDN

This isn't really a feature I want to add personally, but if @houstar wants to do the work and make a pull request I would likely merge it.

**Comment by paulmcgrail** [comment]
I like the idea of push the key with slcli, but not a password less option.

We also have a need for the separation of duties,  not all Portal/slcli users have access to the OS.

The "Easy" button can sometimes problems as well, I don't need VPN access to use slcIi but I do need VPN for ssh, so the functionality might be limited to some, but not all.

On creation of your devices your keys can be added for ssh access.
slcli vs create ...... -k "keyname" or when provisioned via the portal as above..

**Comment by paulmcgrail** [comment]
And after further thought on this,  I think this would add a lot of value to the tool, if you also add...

slcli -VPN ***DataCenter VPNuser*** VPNpassword (-VC "-VC ~/.softlayer-vpn-config" )
slcli ssh --id=12345 " --username ***req*** --password ***optional*** --private_ip or with key  --username "ssh user@private_ip"

**Comment by allmightyspiff** [comment]
Coming back to this issue after 3 years, I think it is something that is just too complicated to maintain for us.

I'm going to close this issue as something we won't be adding. Thanks for the suggestions though, I do appreciate them, even if this one won't be added.
