### ISSUE TITLE
How can I get the secondary address of VM by using API

### ISSUE THREAD

**Issue by esmond88** [softlayer/softlayer-python#846]
I want to use API to get the secondary address of VM. But I cannot find any document about this. Can anyone help me on it.

**Comment by allmightyspiff** [comment]
The API doesn't keep track of what secondary IP address are in use.

Using http://sldn.softlayer.com/reference/services/SoftLayer_Network_Subnet_IpAddress/editObject to set the "note" property of the secondary IP address is the best way to accomplish this via the SoftLayer API.
