### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by paulmcgrail** [softlayer/softlayer-python#873]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
slcli hardware list - should return all hardware devices - Dedicated VSI Host are not returned

### Actual Behavior
Details on all hardware would be return for use,  without the dedicated host ID 
Other actions are not possible without the server/host ID

https://sldn.softlayer.com/reference/datatypes/softlayer_virtual_dedicatedhost
https://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/migrateDedicatedHost
https://softlayer.github.io/python/getdedihostallocation/

### Environment Information
Operating System: Mac OS v10.12.6
softlayer-python version (`slcli --version`):5.2.14
Python version: Python 2.7.13

**Comment by c4po** [comment]
+1

**Comment by allmightyspiff** [comment]
Although not directly in the HW list, dedicated host support was added in 5.3.2. Hopefully this solves your request.

```
$ slcli dedicatedhost list
:.......:...................:..........:..............:................:............:............:
:   id  :        name       : cpuCount : diskCapacity : memoryCapacity : datacenter : guestCount :
:.......:...................:..........:..............:................:............:............:
: 50701 :     ajcb-test     :    56    :     1200     :      242       :   mex01    :     -      :
: 10201 :     dedicated2    :    56    :     1200     :      242       :   dal10    :     -      :
: 64801 : dedicatedHostTest :    56    :     1200     :      242       :   mex01    :     -      :
: 10405 :       fmirDH      :    56    :     1200     :      242       :   dal09    :     2      :
:.......:...................:..........:..............:................:............:............:
```
