### ISSUE TITLE
New Feature Request - Migrate any VSI Device to Dedicated Host

### ISSUE THREAD

**Issue by paulmcgrail** [softlayer/softlayer-python#874]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Migrate VSI Device should migrate any VSI, Public or Dedicated to my Private Dedicated Hosts where I can manage the placement and migration for load balancing and maintenance.

These events are killing us 
ID: 47513421
Type: Planned Event
Subject: VSI Migrations to LTS Hosts -- Service Disruption
Start Date: 08-Sep-2017 17:44 UTC (Sep 08, 2017 01:44PM EDT)
End Date: 20-Oct-2017 00:00 UTC (Oct 19, 2017 08:00PM EDT)
Duration: Longer than a month

### Actual Behavior
Everything I have read and been told the VSI Migrate is Dedicated host Dedicate host only
My test will be done on the very soon and I will update the issue.

Migrating Public Devices to Private Dedicated VSI should be core functionality,  I have not interest in going from Dedicated to Public, but other might.

### Environment Information
Operating System: Mac OS 10.12.6
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.2.14

**Comment by allmightyspiff** [comment]
Sadly, its still not possible to migrate guests between products like you wanted. The only way this would be technically possible, at least from the SLCLI side of things, would be to create an image of Guest A, Create Guest B from that template on a dedicated host, and cancel Guest A.

However, there is likely some value in adding [Migrate](https://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/migrate/) and [MigrateDedicatedHost](https://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/migrateDedicatedHost/) feature. So I'll use this issue to track adding those commands at least.

[Migrate](https://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest/migrate/) should allow you to have some control over when specifically a guest is migrated at least, for future maintenance like this.
