### ISSUE TITLE
Server and VS price calculation is incorrect

### ISSUE THREAD

**Issue by code-noggin** [softlayer/softlayer-python#877]
### Expected Behavior
`slcli server detail --price [id] | grep price_rate ` should match value in https://control.softlayer.com/account/invoices/next

### Actual Behavior
PR https://github.com/softlayer/softlayer-python/pull/763 started adding a sum of all children prices to the total price_rate. Per [SoftLayer_Billing_Item::getNextInvoiceTotalRecurringAmount](https://sldn.softlayer.com/reference/services/softlayer_billing_item/getnextinvoicetotalrecurringamount), children are already included. I suspect this has changed since the PR was merged.

### Environment Information
Operating System: macOS Sierra
softlayer-python version (`slcli --version`): `slcli (SoftLayer Command-line), version 5.2.14`

**Comment by code-noggin** [comment]
@sudorandom What do you think?

**Comment by allmightyspiff** [comment]
sudorandom isn't part of the project anymore, but I'll take a look at this.

**Comment by allmightyspiff** [comment]
This should be fixed in 5.3.2. Thanks.
