### ISSUE TITLE
Is there an API that restart, shutdown and Start a bare metal device ?

### ISSUE THREAD

**Issue by omkartelee08** [softlayer/softlayer-python#878]
I do not find any function in SoftLayer.HardwareManager class that reboots, shutOff or Starts a bare metal device.
Can anyone help me with this ?

**Comment by allmightyspiff** [comment]
No, changing the power state of a server is fairly straight forward, and isn't included in the manager directly. 

http://sldn.softlayer.com/reference/services/SoftLayer_Hardware_Server

You can see how the SLCLI handles this here:
https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/CLI/hardware/power.py
