### ISSUE TITLE
Did softlayer-pytho support getUpgradeItemPrices API?

### ISSUE THREAD

**Issue by EdwardStudy** [softlayer/softlayer-python#892]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**
When I run code below to get upgradeItemPrices:

code:
    client = SoftLayer.create_client_from_env(username=USER, api_key=KEY)

    mask = ['id',
            'categories.id',
            'categories.categoryCode',
            'item.description',
            'item.capacity',
            ]

    fil = {
        'upgradeItemPrices': {
            'categories.categoryCode': {
                'operation': 'guest_disk1'
            }
        }
    }
    result = client.call('SoftLayer_Virtual_Guest', 'getUpgradeItemPrices', mask=string.join(mask, ','), filter=fil)
    print(result)

### Expected Behavior
Return a list of upgradeItemPrices
### Actual Behavior
Return error: SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception): Object does not exist to execute method on. (SoftLayer_Virtual_Guest::getUpgradeItemPrices)

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.2.15

**Comment by kwienken** [comment]
Hi,

The method is still supported. It requires the id of the virtual server you are wanting to get upgrade item prices. Typically when you receive an "Object does not exist to execute method on." error from the SoftLayer API it means that the call requires the id of an existing object.

Try changing the call to 
`result = client.call('SoftLayer_Virtual_Guest', 'getUpgradeItemPrices', id=GUEST_ID mask=string.join(mask, ','), filter=fil)`

Also, the getUpgradeItemPrices call does not support filters so while you can provide them they will not be used.
