### ISSUE TITLE
Cannot find standard price for categoryCode storage_service_enterprise

### ISSUE THREAD

**Issue by tianhw2006** [softlayer/softlayer-python#903]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/storage_utils.py#L116

It should be `if price['locationGroupId'] is not None:`

### Actual Behavior
It tries to find the item which has `locationGroupId` value to be an empty string, which is wrong.

### Environment Information
Operating System: Mac
softlayer-python version (`slcli --version`): 5.3.1

**Comment by tianhw2006** [comment]
Same issue: https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/storage_utils.py#L150

**Comment by allmightyspiff** [comment]
For the default location, the API returns an empty string for locationGroupId, so checking for None would not work.
```json
'currentPriceFlag': '',
 'hourlyRecurringFee': '.866',
 'id': 178055,
 'itemId': 8191,
 'laborFee': '0',
 'locationGroupId': '',
 'onSaleFlag': '',
 'oneTimeFee': '0',
 'quantity': '',
 'recurringFee': '575',
 'setupFee': '0',
 'sort': 0,
 'tierMinimumThreshold': ''}
	178059 - locationGroupId: Location Group 2
```

**Comment by tianhw2006** [comment]
@allmightyspiff Thanks for quick check. However, while I run the following ```    client = SoftLayer.Client(username=sl_user, api_key=sl_api_key)
    filestorage_manager = SoftLayer.FileStorageManager(client)
    result = filestorage_manager.order_file_volume(
        storage_type='endurance',
        location='dal10',
        size=20,
        iops=None,
        tier_level=4,
        service_offering='enterprise'
        )``` I saw the error ```  File "/Library/Python/2.7/site-packages/SoftLayer/managers/file.py", line 343, in order_file_volume
    snapshot_size, service_offering, 'file', hourly_billing_flag
  File "/Library/Python/2.7/site-packages/SoftLayer/managers/storage_utils.py", line 683, in prepare_volume_order_object
    find_price_by_category(package, order_category_code),
  File "/Library/Python/2.7/site-packages/SoftLayer/managers/storage_utils.py", line 125, in find_price_by_category
    % price_category)
ValueError: Could not find price with the category, storage_service_enterprise```Could you help check it? Thanks.
BTW: after I change to `if price['locationGroupId'] is not None:` as I mentioned above, the error is gone.
