### ISSUE TITLE
Request logging and statistics

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#909]
Allow users to opt-in to logging Api requests for debug / error reporting purposes.

## Step 1:
Turn on logging in the .softlayer config file. 
Should have options for
+ Where to log
+ Log API Service and Method
+ Log API request (data being sent)
+ Log API response code
+ Log API response ( data being received)
+ Log start + finish time

## Step 2
keep logs in either plain text or sql light format, not sure what I want to do just yet.

**Comment by allmightyspiff** [comment]
thoughts:
 create a transport wrapper that moves the logging out of the actual transport. along with keeping track of how long api calls take and any results returned.

**Comment by rlrossiter** [comment]
At least from a timing standpoint, there's already a transport for it https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/transports.py#L337

And for the logging, if you turn on info/debugging (or use `-vvvv` on `slcli`), you'll get a dump of the request and response payloads (tons of XML, so it not super useful)

**Comment by allmightyspiff** [comment]
What I'm trying to do is make that logging a bit more useful, rather than just spamming XML all over the terminal. 

I've been playing around with some things in https://github.com/allmightyspiff/softlayer-python/blob/issues909/SoftLayer/transports.py but so far I don't think I've come up with a logging system I like.

**Comment by allmightyspiff** [comment]
added in #960
