### ISSUE TITLE
Get Virtual Server Details from within Softlayer VM

### ISSUE THREAD

**Issue by frostarun** [softlayer/softlayer-python#913]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):

Can we get Virtual Server Details like [aws](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-retrieval) in softlayer ?

**Comment by allmightyspiff** [comment]
The softlayer API is pretty different form the AWS api, so no. If you want to get information about a virtual server that is not in the SLCLI directly, you can create an specific objectMask to get that details.

``bash
$ slcli call-api SoftLayer_Virtual_Guest getObject --id=39338567 --mask="mask[id,hostname,allowedNetworkStorage,backendRouters[hostname]]"
:.......................:..................:
:                  name : value            :
:.......................:..................:
:        backendRouters : :..............: :
:                       : :   hostname   : :
:                       : :..............: :
:                       : : bcr01a.par01 : :
:                       : : bcr01b.par01 : :
:                       : :..............: :
:              hostname : winvsphereparis  :
: allowedNetworkStorage :                  :
:                    id : 39338567         :
:.......................:..................:
```

You can see more examples of objectMasks here: https://softlayer.github.io/tags/objectmask/
