### ISSUE TITLE
order item-list should display category

### ISSUE THREAD

**Issue by allmightyspiff** [softlayer/softlayer-python#918]
not really any way to correlate a item with category at the moment.

**Comment by allmightyspiff** [comment]
Also need a way to find locations for packages

**Comment by rlrossiter** [comment]
There is `slcli order item-list --category <category>` to list items only in a certain category, but yeah, when you do the entire list there's no way right now to have it list the categories an item is in.

**Comment by allmightyspiff** [comment]
added in 5.4.0
