### ISSUE TITLE
New Feature - Allow credentials to be passed as flags

### ISSUE THREAD

**Issue by lcopi** [softlayer/softlayer-python#928]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Allow username and apikey to be passed as arguments to `slcli setup` or `slcli config setup`
Example: `slcli setup --username <username> --apikey <apikey>`
### Actual Behavior
Currently when running setup for the cli there are only two ways to pass your login information: through the user prompts or by creating a config file. This makes it difficult to use the cli within a script
### Environment Information
Operating System:
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.3.2

**Comment by allmightyspiff** [comment]
`slcli setup` simply creates the ~/.softlayer file

For remote setups, I would recommend just creating that file with whatever automation you are using. 

environment variables can also be used. Setting `SL_USERNAME` and `SL_API_KEY` should allow you to bypass `slcli setup` as well.

https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/config.py#L32
