### ISSUE TITLE
New Feature - support publishing image through cli

### ISSUE THREAD

**Issue by lcopi** [softlayer/softlayer-python#929]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
A cli or api function that allows users to make an image public with an image guid
### Actual Behavior
Currently the only way to publish images is using the softlayer console. It would be much more effective to create an api endpoint to publish images through the cli so image build processes can be automated
### Environment Information
Operating System:
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.3.2

**Comment by svlady** [comment]
There is a programmatic way, take a look at this blog post https://www.ibm.com/cloud/blog/speed-up-image-imports-to-ibm-cloud-infrastructure

**Comment by allmightyspiff** [comment]
I believe this feature was added a while back, as  [slcli image import](https://softlayer-python.readthedocs.io/en/latest/cli/image/#image-import) and [slcli image export](https://softlayer-python.readthedocs.io/en/latest/cli/image/#image-export). Allowing you to import/export to the ibmcloud object storage container.
