### ISSUE TITLE
Clarify for security group add rule how to specify ICMP type/code 

### ISSUE THREAD

**Issue by unterhol** [softlayer/softlayer-python#930]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Running  'slcli sg rule-add --help'  would clarify that port-min and port-max parameters are used to specify which icmp type and code the rule will permit.

### Actual Behavior
Running  'slcli sg rule-add --help'  does not clarify that port min/max are overloaded this way. 

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.2.14

**Comment by rlrossiter** [comment]
```
(venv) ryans-mbp-2:softlayer-python rlrossit$ slcli sg rule-add --help
Usage: slcli sg rule-add [OPTIONS] SECURITYGROUP_ID

  Add a security group rule to a security group.

Options:
  -r, --remote-ip TEXT        The remote IP/CIDR to enforce
  -s, --remote-group INTEGER  The ID of the remote security group to enforce
  -d, --direction TEXT        The direction of traffic to enforce (ingress,
                              egress)
  -e, --ethertype TEXT        The ethertype (IPv4 or IPv6) to enforce
  -M, --port-max INTEGER      The upper port bound to enforce. When the
                              protocol is ICMP, this specifies the ICMP code
                              to permit
  -m, --port-min INTEGER      The lower port bound to enforce. When the
                              protocol is ICMP, this specifies the ICMP type
                              to permit
  -p, --protocol TEXT         The protocol (icmp, tcp, udp) to enforce
  -h, --help                  Show this message and exit.
```
Here's a working copy of the documentation to add to min (type) and max (code). To be a little more explicit I may add a couple examples to the rule-add help as well. One for TCP (SSH) and one for ICMP (ping).
