### ISSUE TITLE
edit-securitygroup-rules cannot clear out field

### ISSUE THREAD

**Issue by bvanhav** [softlayer/softlayer-python#932]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
When editing a security group rule using the SLDN API, a string field (for example remote_ip) can be cleared by passing in an empty string. If an empty string is passed to the network manager edit_securitygroup_rule, that empty string should be passed to SLDN and the field cleared.

### Actual Behavior
The empty string is not passed to SLDN and the 'edited' rule returns with the 'cleared' field still set to its original value.

### Environment Information
Operating System:
softlayer-python version (`slcli --version`): 5.2.14

**Comment by allmightyspiff** [comment]
This fix has been merged. Should be included in 5.4.1
