### ISSUE TITLE
import softlayer returns no such module on Mac High Sierra

### ISSUE THREAD

**Issue by jgnoonan** [softlayer/softlayer-python#934]
I’m running a iMac (Late 2016) with High Sierra 10.13.2. If I open Python 2.7.14 and run import softlayer I get an error that the module isn’t found. How do I fix this. 

**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):

**Comment by camporter** [comment]
You will need to install the `softlayer` module into your environment. I'd recommend against installing the `softlayer` package into the system packages though. Instead, I'd look up how to use `virtualenv`.

A good place to get more information about best practices would be something like: http://docs.python-guide.org/en/latest/dev/virtualenvs/
