### ISSUE TITLE
Feature request: get_instance by hostname or IP address

### ISSUE THREAD

**Issue by PedroMVM** [softlayer/softlayer-python#942]
Please include option to use _get_instance_ using IP address or hostname. Currently I have to use _list_instances_ and search for host ID. It is taking a long time to get list of all instances.

### Expected Behavior
_get_instance_ new parameters to find instance by hostname or IP address

### Actual Behavior
_get_instance_ find instance only with host ID

### Environment Information
Operating System: Windows
softlayer-python version (`slcli --version`): 5.4.1

**Comment by allmightyspiff** [comment]
`list_instance` supports filtering based off hostname and ipaddress. 

https://softlayer-python.readthedocs.io/en/latest/api/managers/vs.html#SoftLayer.managers.vs.VSManager.list_instances


The VS manager has 2 resolvers that do what you want as well. 

```
    def _get_ids_from_hostname(self, hostname):
        """List VS ids which match the given hostname."""
        results = self.list_instances(hostname=hostname, mask="id")
        return [result['id'] for result in results]

    def _get_ids_from_ip(self, ip_address):  # pylint: disable=inconsistent-return-statements
        """List VS ids which match the given ip address."""
        try:
            # Does it look like an ip address?
            socket.inet_aton(ip_address)
        except socket.error:
            return []

        # Find the VS via ip address. First try public ip, then private
        results = self.list_instances(public_ip=ip_address, mask="id")
        if results:
            return [result['id'] for result in results]

        results = self.list_instances(private_ip=ip_address, mask="id")
        if results:
            return [result['id'] for result in results]
```

Currently using list_instance with a filter is going to be the best way to find the ID of a guest from a hostname or ip. 

I hope that helps explain how to do what you want. Let me know if that wasn't what you were looking for.

**Comment by PedroMVM** [comment]
Ok, it does work, but that is not intuitive. As I wish only one instance it would be better using `get_instance` (notice the singular), while `list_instances` is used to get more than one (notice the plural). I also have to `pop` the instance out of the list, while `get_instance` gives it as an object.

This is just an opinion, not a criticism.
