### ISSUE TITLE
"slcli ticket upload" fails with PDF files at least

### ISSUE THREAD

**Issue by PYLochou** [softlayer/softlayer-python#948]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Same as .txt file for instance:

$ slcli ticket upload --path /home/lochou/Documents/IBMCAPKI-french.txt --name test.txt 55879893
File attached: 
{'modifyDate': '', 'createDate': '2018-02-26T15:28:43+01:00', 'fileName': 'test.txt', 'uploaderType': 'USER', 'updateId': 347189307, 'fileSize': '1472', 'uploaderId': '184308', 'ticket': {'modifyDate': '2018-02-26T15:28:44+01:00', 'billableFlag': '', 'serverAdministrationBillingAmount': '', 'notifyUserOnUpdateFlag': False, 'responsibleBrandId': 1, 'id': 55879893, 'accountId': 317828, 'totalUpdateCount': 3, 'title': 'API Question - Test', 'createDate': '2018-02-26T15:15:08+01:00', 'serverAdministrationBillingInvoiceId': '', 'priority': 0, 'serverAdministrationFlag': 0, 'serviceProviderResourceId': 55879893, 'originatingIpAddress': '195.212.29.191', 'subjectId': 1522, 'locationId': '', 'serviceProviderId': 1, 'groupId': 1008, 'changeOwnerFlag': False, 'lastEditType': 'USER', 'lastEditDate': '2018-02-26T15:28:44+01:00', 'serverAdministrationRefundInvoiceId': '', 'euSupportedLocationId': '', 'userEditableFlag': True, 'lastResponseDate': '2018-02-26T15:28:43+01:00', 'assignedUserId': 184308, 'statusId': 1001}, 'ticketId': 55879893, 'id': 1030083}

### Actual Behavior
With same environment (same data in ~/.softlayer):

$ slcli ticket upload --path /home/lochou/Documents/vsphere-50-configuration-maximums.pdf --name test.pdf 55879893
SoftLayerAPIError(SoftLayer_Ticket): No valid authentication headers found.

### Environment Information
Operating System: IBM OpenClient 7.4 (ie RHEL 7.4)
softlayer-python version (`slcli --version`): slcli (SoftLayer Command-line), version 5.4.2

**Comment by FernandoOjeda** [comment]
@PYLochou The error that you got is because you did not enter the credentials to be able to make the request.
The slcli command that you are using to upload a file works correctly.
Enter your credentials following the instructions in the tutorial below and then try again your request:
https://softlayer-api-python-client.readthedocs.io/en/latest/cli/
