### ISSUE TITLE
Verification flavor-based VSI order failed for hourly VSIs

### ISSUE THREAD

**Issue by losdevnull** [softlayer/softlayer-python#953]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

We have the following code for VSI order verification based on flavor that used to work fine, but since today it is breaking.
```
order_data = {'domain': u'dev.local', 'userdata': '', 'datacenter': u'tor01', 'dedicated': False, 'private': True, 'nic_speed': 1000, 'private_vlan': 2256635, 'flavor': u'B1_4X8X100', 'hourly': True, 'hostname': u'zerto', 'os_code': u'WIN_2012-STD-R2_64', 'local_disk': False, 'post_uri': ''}
mgr = SoftLayer.VSManager(client)
mgr.verify_create_instance(**order_data)
```

If the above code was changed to `'hourly': False`,  then verification would work.   So something could be changed recently in SL API.   I know this is not necessarily an softlayer-python client problem, but from SL ticket having an issue opened here was suggested to reach SL API team.

### Expected Behavior
Should pass the verification. 

### Actual Behavior
The following error returned from SL API
```
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_Public): Preset with key name B1_4X8X100 could not be found.
```

### Environment Information
Operating System:  MacOS
softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.2.14

**Comment by losdevnull** [comment]
This is significantly impacting our production service, please help address it ASAP.  Thanks.

**Comment by allmightyspiff** [comment]
@losdevnull were looking into this.

**Comment by camporter** [comment]
Changes made to the virtual service have been reverted so that hourly virtual flavor orders no longer error.

Please retry the requests.
