### ISSUE TITLE
Incorrect IOPS max limit for Performance tier volumes

### ISSUE THREAD

**Issue by AugieMena3** [softlayer/softlayer-python#954]
### Expected Behavior
The CLI should be showing 48000 as the maximum limit for Performance storage IOPS in order to match what is (correctly) displayed via the UI.
![iops](https://user-images.githubusercontent.com/8967873/37528683-42f1038a-2903-11e8-9be0-ad12ae1503c6.gif)

### Actual Behavior
However, what's shown via the CLI is 6000 instead.

$ slcli file volume-order --help
Usage: slcli file volume-order [OPTIONS]

  Order a file storage volume.

Options:
  --storage-type [performance|endurance]
                                  Type of file storage volume  [required]
  --size INTEGER                  Size of file storage volume in GB
                                  [required]
  --iops INTEGER                  Performance Storage IOPs, between 100 and
                                  6000 in multiples of 100  [required for
                                  storage-type performance]
  --tier [0.25|2|4|10]            Endurance Storage Tier (IOP per GB)
                                  [required for storage-type endurance]
  --location TEXT                 Datacenter short name (e.g.: dal09)
                                  [required]
  --snapshot-size INTEGER         Optional parameter for ordering snapshot
                                  space along with endurance file storage;
                                  specifies the size (in GB) of snapshot space
                                  to order
  --service-offering [storage_as_a_service|enterprise|performance]
                                  The service offering package to use for
                                  placing the order [optional, default is
                                  'storage_as_a_service']
  --billing [hourly|monthly]      Optional parameter for Billing rate (default
                                  to monthly)
  -h, --help                      Show this message and exit.

### Environment Information
Operating System:
softlayer-python version (`slcli --version`):
$ slcli --version
slcli (SoftLayer Command-line), version 5.4.2

**Comment by allmightyspiff** [comment]
I've fixed this in 5.4.4 : Added a link to the documentation describing the valid iops values (as they tend to change), and removed any text referencing what those values should be. 

the CLI will take in any integer and just pass it to the SLAPI.

```
  slcli file volume-order --help
Usage: slcli file volume-order [OPTIONS]

  Order a file storage volume.

  Valid size and iops options can be found here: https://console.bluemix.net/docs/infrastructure/FileStorage/index.html#provisioning

Options:
  --storage-type [performance|endurance]
                                  Type of file storage volume  [required]
  --size INTEGER                  Size of file storage volume in GB  [required]
  --iops INTEGER                  Performance Storage IOPs. Options vary based on storage size.
                                  [required for storage-type performance]
  --tier [0.25|2|4|10]            Endurance Storage Tier (IOP per GB) [required for storage-type endurance]
  --location TEXT                 Datacenter short name (e.g.: dal09)  [required]
  --snapshot-size INTEGER         Optional parameter for ordering snapshot space along with endurance file storage; specifies the size (in GB) of snapshot
                                  space to order
  --service-offering [storage_as_a_service|enterprise|performance]
                                  The service offering package to use for placing the order.
                                  [optional, default is 'storage_as_a_service']. enterprise and
                                  performance are depreciated
  --billing [hourly|monthly]      Optional parameter for Billing rate (default to monthly)
  -h, --help                      Show this message and exit.
```
