### ISSUE TITLE
Could not obtain network VLAN with id #2032693

### ISSUE THREAD

**Issue by karcio** [softlayer/softlayer-python#968]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
I have a script which provision 4 VMs in softlayer, 3 VMs have the same params and create success, last one fails, only difference between 3VMs and 4th is:
3 Vm (success) requesting - private ip only
1Vm (fails) requesting - public IP & private ip

### Actual Behavior 
Traceback (most recent call last):
  File "./provision_.py", line 81, in <module>
    main()
  File "./provision_.py", line 56, in main
    ids.append(utils.Provision(client, **config.web_vsi));
  File "bin/utils.py", line 16, in Provision
    vsi = mgr.create_instance(**new_vsi)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/managers/vs.py", line 558, in create_instance
    inst = self.guest.createObject(self._generate_create_dict(**kwargs))
  File "/usr/lib64/python2.7/site-packages/SoftLayer/API.py", line 390, in call_handler
    return self(name, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/API.py", line 358, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/API.py", line 261, in call
    return self.transport(request)
  File "/usr/lib64/python2.7/site-packages/SoftLayer/transports.py", line 230, in __call__
    raise _ex(ex.faultCode, ex.faultString)
SoftLayer.exceptions.SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_Public): Could not obtain network VLAN with id #2032693.

### Environment Information
Operating System:
RHEL 7

softlayer-python version (`slcli --version`):
slcli (SoftLayer Command-line), version 5.4.4

**Comment by allmightyspiff** [comment]
Without knowing more about your account and the exact command your using to order its hard to say what the exact problem is, but my guess is that you are trying to order vm 4 with a private vlan ( 2032693 )  on the public ethernet port.

If that isn't the case, could you post the code your using to order vm 4?

**Comment by karcio** [comment]
Hi @allmightyspiff 
Sorry for delay. Could you please remove my issue?  
In this case it is not softlayer-python issue. id 2032693 was removed, used other id and works fine.
