### ISSUE TITLE
#952 Closed ID.....but still stuck without any deployment of vyatta on Softlayer

### ISSUE THREAD

**Issue by AnishAnil** [softlayer/softlayer-python#970]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

### Expected Behavior
Should have deployed an instance of Vyatta
### Actual Behavior
Deploying a simple Vyatta instance fails and does not provide any outputs
### Environment Information

Operating System:MAC
slcli --version
slcli (SoftLayer Command-line), version 5.4.4

Code used as provided in the link provided for #952 

https://softlayer.github.io/python/orderVyatta/

import SoftLayer
from SoftLayer.managers import ordering
import sys
from  pprint import pprint as pp
import logging

logging.debug("Starting up")
# Requires softlayer-python 5.4.3+

class vyattaOrderer():

    def __init__(self):
        if SoftLayer.__version__ < 'v5.4.3':
            print("SoftLayer needs to be 5.4.3+, is currently %s" % SoftLayer.__version__)
        self.client = SoftLayer.Client()
        # slcli order package-list --package_type BARE_METAL_GATEWAY 
        # Will get you available package keynames
        self.package_keyname = "2U_NETWORK_GATEWAY_APPLIANCE_1O_GBPS"
        self.complex_type = 'SoftLayer_Container_Product_Order_Hardware_Server_Gateway_Appliance'

    def orderVyatta(self, dc, pub_vlan='', prv_vlan=''):
        """Actually orders a vyatts
            Required
                - dc
                - Server Chassis
                - RAM
                - OS (not really though)
                - HD (number, raid, partition)
                - Bandwidth 
                - Port Speed
                - IPv6
            Options
                - vlans
                - provision scrips
                - ssh keys
                - userdata
                - hostname, domain
        """
        
        order_svc = self.client['Product_Order']

        order_items = self.itemKeynameList()

        extras = {}
        extras['hardware'] = [
            self.generateHardwareEntry('vyatta1', 'test.com', pub_vlan, prv_vlan, 'vyatta1 Test')
        ]
        extras['storageGroups'] = [self.generateRaidEntry()]
        extras['sshKeys'] = [{'sshKeyIds': [87634]}]
        extras['provisionScripts'] = [
        'https://raw.githubusercontent.com/softlayer/softlayer.github.io/master/provision-test.sh'
        ]

        vyatta_order = self.getOrderObject(dc, order_items, extras, 1)
        order_object = {
            'orderContainers': [
                vyatta_order
            ]
        }

        #verify = order_svc.verifyOrder(order_object)
        verify = order_svc.placeOrder(order_object)
        pp(verify)
        print("done")

Observed behavior:

Both verify and deploy simply comes out clean without any outputs.

Where do we specify the user-id and api-key which was available in the previous version of the code and not in this one??

Is there a sample file with all these data filled out that we could refer.......
This is critical as it is stopping our automated deployments.

Any help is greatly appreciated.

Thank you,
Anish

**Comment by allmightyspiff** [comment]
If you copied the entire script from the example and ran it, you should  be getting either an error, or a full order object returned. If you didn't get any output, I suspect your missing some bits of the script and the code just isn't running.

User name and apikey are usually read from ~/.softlayer file. They can be specified as arguments to SoftLayer.Client() ( read https://softlayer-python.readthedocs.io/en/latest/api/client.html#getting-started )

This is the exact order container that would get generated. Replace location with the location id you want to order it in. 2178495 is sjc04.
```
{'orderContainers': [{'complexType': 'SoftLayer_Container_Product_Order_Hardware_Server_Gateway_Appliance',
                      'hardware': [{'domain': 'test.com',
                                    'hostname': 'vyatta1'}],
                      'location': 2178495,
                      'packageId': 236,
                      'prices': [{'id': 58},
                                 {'id': 55},
                                 {'id': 57},
                                 {'id': 906},
                                 {'id': 418},
                                 {'id': 420},
                                 {'id': 792},
                                 {'id': 342},
                                 {'id': 2397},
                                 {'id': 21},
                                 {'id': 17129},
                                 {'id': 14031},
                                 {'id': 14031},
                                 {'id': 1915},
                                 {'id': 17182},
                                 {'id': 201189},
                                 {'id': 46541}],
                      'quantity': 1,
                      'useHourlyPricing': False}]}

```
