### ISSUE TITLE
TicketManager  list_tickets returns all tickets when it should return none

### ISSUE THREAD

**Issue by duncan1117** [softlayer/softlayer-python#977]
**Please triple-check to make sure that you have properly masked out user credentials like usernames, passwords and API keys before submitting your issue**

`mgr = SoftLayer.TicketManager(client.create_sldn_client())`
`mgr.list_tickets(open_status=False, closed_status=False)`

### Expected Behavior
Should return an empty list
### Actual Behavior
returns list of all tickets, as if I had said True for both parameters.
### Environment Information
Operating System:  Win 7
softlayer-python version (`slcli --version`):  5.4.0

**Comment by allmightyspiff** [comment]
Should be fixed in #989
