### ISSUE TITLE
SLCLI - Baremetal servers cannot be ordered with two gpu items

### ISSUE THREAD

**Issue by acamacho82** [softlayer/softlayer-python#985]
This is for baremetal servers which have GPU support.

### Expected Behavior
- It should be possible to order baremetal servers with two gpu items
- The user should be able to select gpu0 or gpu1 if he wants only one item of this type (like the portal).

### Actual Behavior

This is related to #983 and #984

It seems that currently there is no way to order a baremetal with two gpu items like in the portal page, the only way is through the placeOrder method.

Below is the command I tried, I sent the keyName of the gpu device twice but it returns an error

`$ slcli order place --verify  --billing monthly --complex-type SoftLayer_Container_Product_Order_Hardware_Server DUAL_E52600_V4_12_DRIVES DALLAS12 REBOOT_KVM_OVER_IP UNLIMITED_SSL_VPN_USERS_1_PPTP_VPN_USER_PER_ACCOUNT NESSUS_VULNERABILITY_ASSESSMENT_REPORTING NOTIFICATION_EMAIL_AND_TICKET 1_IP_ADDRESS AUTOMATED_NOTIFICATION MONITORING_HOST_PING BANDWIDTH_500_GB REDUNDANT_POWER_SUPPLY INTEL_TXT_TRUSTED_EXECUTION_TECHNOLOGY OS_UBUNTU_16_04_LTS_XENIAL_XERUS_MINIMAL_64_BIT INTEL_INTEL_XEON_E52620_V4_2_10 RAM_128_GB_DDR4_2133_ECC_REG 10_GBPS_REDUNDANT_PUBLIC_PRIVATE_NETWORK_UPLINKS DISK_CONTROLLER_NONRAID HARD_DRIVE_1_9TB_SSD_SED_5DWPD HARD_DRIVE_2_00_TB_SATA_2  HARD_DRIVE_3_8TB_SSD_SED_3DWPD GPU_NVIDIA_TESLA_K80 GPU_NVIDIA_TESLA_K80`

`
SoftLayerAPIError(SoftLayer_Exception_Public): Unable to add NVIDIA Tesla K80 Graphic Card because the same price has already been added for Secondary Graphics Processing Unit.
`
### Environment Information
Operating System: Linux, Windows
softlayer-python version (`slcli --version`): 5.4.4

**Comment by allmightyspiff** [comment]
Should be fixed in the next release
